import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'he' | 'en' | 'ar' | 'ru' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  he: {
    // Header
    'nav.home': 'בית',
    'nav.cookies': 'עוגיות',
    'nav.about': 'אודות',
    'nav.reviews': 'ביקורות',
    'nav.faq': 'שאלות נפוצות',
    'nav.contact': 'צור קשר',
    'nav.cart': 'עגלה',
    'nav.profile': 'פרופיל',
    'nav.login': 'התחברות',
    'nav.logout': 'התנתקות',
    'nav.orderHistory': 'היסטוריית הזמנות',
    'nav.editProfile': 'עריכת פרופיל',
    
    // Hero
    'hero.title': 'מזון האושר',
    'hero.subtitle': 'עוגיות אמריקאיות ענקיות',
    'hero.description': 'עוגיות אמריקאיות ענקיות בעבודת יד, עשויות מחומרי הגלם הטובים ביותר',
    'hero.cta': 'לתפריט העוגיות',
    'hero.madeWithLove': 'מיוצר באהבה',
    'hero.viewMenu': 'צפו בתפריט',
    
    // Cookies Section
    'cookies.title': 'הקולקציה שלנו',
    'cookies.subtitle': 'מיוצר באהבה, במיוחד בשבילכם ✨',
    'cookies.addToCart': 'הוסף לעגלה',
    'cookies.outOfStock': 'אזל מהמלאי',
    'cookies.price': '₪',
    'cookies.search': 'חיפוש...',
    'cookies.all': 'הכל',
    'cookies.chocolate': 'שוקולד',
    'cookies.fruits': 'פירות',
    'cookies.candy': 'ממתקים',
    'cookies.nuts': 'אגוזים',
    'cookies.classic': 'קלאסי',
    'cookies.recommended': 'מומלץ',
    'cookies.new': 'חדש',
    'cookies.favorites': 'מועדפים',
    'cookies.sortDefault': 'ברירת מחדל',
    'cookies.sortName': 'לפי שם',
    'cookies.sortPrice': 'לפי מחיר',
    'cookies.noResults': 'לא נמצאו עוגיות',
    'cookies.clearFilters': 'נקה מסננים',
    
    // Cookie names
    'cookie.lotus': 'לוטוס',
    'cookie.kinder': 'קינדר',
    'cookie.kinderBueno': 'קינדר בואנו',
    'cookie.redVelvet': 'רד וולווט',
    'cookie.confetti': 'קונפטי',
    'cookie.pistachio': 'פיסטוק',
    'cookie.pretzel': 'בייגלה',
    'cookie.chocolateChip': 'שוקולד צ׳יפס',
    'cookie.oreo': 'אוראו',
    'cookie.peanutButter': 'חמאת בוטנים',
    'cookie.lemon': 'לימון',
    'cookie.macadamia': 'מקדמיה',
    'cookie.oatmeal': 'שיבולת שועל',
    'cookie.saltedCaramel': 'קרמל מלוח',
    'cookie.tahini': 'טחינה',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'ביסקוויט לוטוס וממרח קרמל',
    'cookie.kinderDesc': 'שוקולד קינדר וכדורי שוקולד צבעוניים',
    'cookie.kinderBuenoDesc': 'קינדר בואנו, שוקולד חלב וציפוי שוקולד',
    'cookie.redVelvetDesc': 'בצק רד וולווט, שוקולד לבן ופירורי פטל',
    'cookie.confettiDesc': 'סוכריות צבעוניות וסמארטיז',
    'cookie.pistachioDesc': 'שוקולד לבן, פיסטוקים קלויים וגרגירי רימון',
    'cookie.pretzelDesc': 'בייגלה מלוח, שוקולד לבן וצ׳יפס שוקולד',
    'cookie.chocolateChipDesc': 'צ׳יפס שוקולד בלגי מריר ושוקולד חלב',
    'cookie.oreoDesc': 'פירורי אוראו, שוקולד לבן וקרם וניל',
    'cookie.peanutButterDesc': 'חמאת בוטנים, בוטנים קלויים ושוקולד',
    'cookie.lemonDesc': 'גרידת לימון טרי וציפוי סוכר',
    'cookie.macadamiaDesc': 'אגוזי מקדמיה ושוקולד לבן',
    'cookie.oatmealDesc': 'שיבולת שועל, צימוקים וקינמון',
    'cookie.saltedCaramelDesc': 'קרמל ביתי וקריסטלי מלח ים',
    'cookie.tahiniDesc': 'טחינה גולמית, שומשום ודבש',
    
    // Cookie of the Week
    'cotw.title': 'עוגיית השבוע',
    'cotw.discount': 'הנחה',
    'cotw.originalPrice': 'מחיר מקורי',
    'cotw.salePrice': 'מחיר מבצע',
    
    // About
    'about.title': 'אודות מזון האושר',
    'about.ourStory': 'הסיפור שלנו',
    'about.headline': 'יוצרים אושר, יצירה אחת בכל פעם',
    'about.description': 'מזון האושר התחיל במטבח ביתי קטן עם חלום פשוט: לשתף את החום והנוחות של מאפים ביתיים עם הקהילה שלנו.',
    'about.madeWithLove': 'מיוצר באהבה',
    'about.madeWithLoveDesc': 'כל אצווה מוכנה בקפידה ובתשוקה, בדיוק כמו שסבתא הייתה עושה.',
    'about.freshIngredients': 'מרכיבים טריים',
    'about.freshIngredientsDesc': 'אנחנו מקפידים רק על המרכיבים הטריים והמשובחים ביותר.',
    'about.dailyPrep': 'הכנה יומית',
    'about.dailyPrepDesc': 'המוצרים שלנו מוכנים טריים כל בוקר לטעם מושלם.',
    
    // Reviews
    'reviews.title': 'מה הלקוחות אומרים',
    'reviews.subtitle': 'ביקורות מלקוחות מרוצים',
    'reviews.addReview': 'הוסיפו ביקורת',
    'reviews.selectProduct': 'בחרו מוצר',
    'reviews.selectProductPlaceholder': 'בחרו מוצר...',
    'reviews.rating': 'דירוג',
    'reviews.yourReview': 'הביקורת שלכם (אופציונלי, עד 500 תווים)',
    'reviews.reviewPlaceholder': 'ספרו לנו מה חשבתם...',
    'reviews.submit': 'לשלוח ביקורת',
    'reviews.submitting': 'שולח...',
    'reviews.loginRequired': 'כדי לכתוב ביקורת צריך להתחבר',
    'reviews.recentReviews': 'ביקורות אחרונות',
    'reviews.filterAll': 'כל המוצרים',
    'reviews.noReviews': 'אין עדיין ביקורות. היו הראשונים לכתוב ביקורת!',
    'reviews.thankYou': 'תודה על הביקורת! 🍪',
    'reviews.reviewAdded': 'הביקורת שלך נוספה בהצלחה',
    'reviews.reviewsCount': 'ביקורות',
    
    // FAQ
    'faq.title': 'שאלות נפוצות',
    'faq.subtitle': 'כאן תמצאו תשובות לשאלות הנפוצות ביותר. לא מצאתם מה שחיפשתם? צרו איתנו קשר!',
    'faq.delivery': 'איך עובד המשלוח?',
    'faq.deliveryAnswer': 'המשלוחים מתבצעים בימים א׳-ה׳ בשעות 10:00-20:00. המשלוח עולה ₪25 לכל הארץ, ומשלוח חינם בהזמנות מעל ₪150. זמן האספקה הוא 1-3 ימי עסקים.',
    'faq.payment': 'אילו אמצעי תשלום מקבלים?',
    'faq.paymentAnswer': 'כרגע אנחנו מקבלים תשלום במזומן בלבד בעת קבלת המשלוח. בקרוב נוסיף אפשרות לתשלום בכרטיס אשראי.',
    'faq.freshness': 'כמה זמן המוצרים נשמרים טריים?',
    'faq.freshnessAnswer': 'המוצרים שלנו מוכנים טריים לכל הזמנה ונשמרים טריים עד 5 ימים בטמפרטורת החדר או עד שבועיים במקרר. מומלץ לחמם במיקרוגל 10 שניות לחוויה מושלמת!',
    'faq.allergens': 'מה לגבי אלרגנים?',
    'faq.allergensAnswer': 'כל העוגיות שלנו מכילות גלוטן, חלב וביצים. חלק מהעוגיות מכילות אגוזים, בוטנים או סויה. אם יש לכם אלרגיה מסוימת, אנא ציינו בהערות ההזמנה ונתאים עבורכם.',
    'faq.events': 'האם אפשר להזמין לאירועים?',
    'faq.eventsAnswer': 'בהחלט! אנחנו מציעים חבילות מיוחדות לאירועים, ימי הולדת, חתונות ובת/בר מצווה. צרו איתנו קשר לקבלת הצעת מחיר מותאמת אישית.',
    'faq.contact': 'איך יוצרים איתכם קשר?',
    'faq.contactAnswer': 'אפשר ליצור קשר דרך הוואטסאפ בכפתור הצף למטה, דרך הטופס באתר, או בטלפון 054-6791198. אנחנו זמינים בימים א׳-ה׳ בין השעות 9:00-21:00.',
    
    // Contact
    'contact.title': 'צרו קשר',
    'contact.address': 'שדרות קדש 39, אשקלון',
    'contact.phone': '054-679-1198',
    'contact.hours': 'אספקה עד 3 ימי עסקים',
    
    // Cart
    'cart.title': 'העגלה שלך',
    'cart.empty': 'העגלה ריקה',
    'cart.total': 'סה"כ',
    'cart.checkout': 'לתשלום',
    'cart.remove': 'הסר',
    'cart.quantity': 'כמות',
    'cart.subtotal': 'סכום ביניים',
    'cart.shipping': 'משלוח',
    'cart.free': 'חינם',
    
    // Checkout
    'checkout.title': 'פרטי הזמנה',
    'checkout.name': 'שם מלא',
    'checkout.phone': 'טלפון',
    'checkout.address': 'כתובת',
    'checkout.city': 'עיר',
    'checkout.notes': 'הערות להזמנה',
    'checkout.submit': 'שלח הזמנה',
    'checkout.success': 'ההזמנה נשלחה בהצלחה!',
    
    // Auth (basic - extended auth keys are at the end of Hebrew section)
    'auth.login': 'התחברות',
    'auth.signup': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.loginButton': 'התחבר',
    'auth.signupButton': 'הירשם',
    'auth.orContinueWith': 'או המשך עם',
    'auth.phoneLogin': 'התחברות עם טלפון',
    'auth.verifyCode': 'אמת קוד',

    // Profile
    'profile.title': 'הפרופיל שלי',
    'profile.edit': 'ערוך פרופיל',
    'profile.save': 'שמור',
    'profile.cancel': 'ביטול',
    'profile.deleteAccount': 'מחיקת חשבון',
    'profile.changePassword': 'שנה סיסמה',
    
    // Newsletter
    'newsletter.title': 'לא לפספס מבצעים!',
    'newsletter.subtitle': 'הירשמו לניוזלטר וקבלו עדכונים על מבצעים מיוחדים',
    'newsletter.emailPlaceholder': 'כתובת המייל שלך',
    'newsletter.phonePlaceholder': 'מספר טלפון (אופציונלי)',
    'newsletter.button': 'להירשם לעדכונים ✨',
    'newsletter.submitting': 'שולח...',
    'newsletter.success': 'נרשמת בהצלחה! 🎉',
    'newsletter.successDesc': 'תקבל/י עדכונים על מבצעים וחדשות',
    'newsletter.thankYou': 'תודה שנרשמת! ✨',
    'newsletter.thankYouDesc': 'נעדכן אותך על מבצעים מיוחדים, מוצרים חדשים והפתעות מתוקות',
    'newsletter.noSpam': 'אנחנו מבטיחים לא לשלוח ספאם. רק טוב טעים. ✨',
    
    // Footer
    'footer.rights': 'כל הזכויות שמורות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    
    // General
    'general.loading': 'טוען...',
    'general.error': 'שגיאה',
    'general.success': 'הצלחה',
    'general.close': 'סגור',
    'general.back': 'חזרה',
    'general.next': 'הבא',
    'general.confirm': 'אישור',
    'general.delete': 'מחק',
    'general.edit': 'ערוך',
    'general.save': 'שמור',
    'general.cancel': 'ביטול',
    
    // Gift Package
    'gift.title': 'חבילות מתנה',
    'gift.subtitle': 'בנו חבילת מתנה מושלמת עם העוגיות האהובות עליכם',
    'gift.selectCookies': 'בחרו עוגיות למארז',
    'gift.packageName': 'שם המארז',
    'gift.packageNameOptional': 'שם החבילה (אופציונלי)',
    'gift.packageNamePlaceholder': 'למשל: מתנה ליום הולדת',
    'gift.addToCart': 'להוסיף לעגלה',
    'gift.small': 'חבילה קטנה',
    'gift.medium': 'חבילה בינונית',
    'gift.large': 'חבילה גדולה',
    'gift.smallDesc': '6 עוגיות לבחירתך',
    'gift.mediumDesc': '12 עוגיות לבחירתך',
    'gift.largeDesc': '24 עוגיות לבחירתך',
    'gift.discount': 'הנחה',
    'gift.selected': 'נבחרו',
    'gift.outOf': 'מתוך',
    'gift.moreToSelect': 'עוד {count} לבחירה',
    'gift.packageFull': 'החבילה מלאה!',
    'gift.packageFullError': 'החבילה מלאה',
    'gift.alreadySelected': 'בחרת כבר {count} עוגיות',
    'gift.yourCookies': 'העוגיות שבחרתם',
    'gift.regularPrice': 'מחיר רגיל:',
    'gift.packageDiscount': 'הנחת חבילה',
    'gift.total': 'סה״כ:',
    'gift.notComplete': 'החבילה לא מלאה',
    'gift.selectMore': 'נא לבחור {count} עוגיות נוספות',
    'gift.addedToCart': 'החבילה נוספה לעגלה! 🎁',
    'gift.cookies': 'עוגיות',
    
    // Cookie of the Week
    'cotw.badge': 'עוגיית השבוע',
    'cotw.add': 'הוספה',
    
    // Cart Modal
    'cartModal.title': 'העגלה שלי',
    'cartModal.completing': 'השלמת הזמנה',
    'cartModal.empty': 'העגלה ריקה',
    'cartModal.addCookies': 'הוסיפו עוגיות טעימות!',
    'cartModal.cookies': 'עוגיות',
    'cartModal.saved': 'חסכת',
    'cartModal.total': 'סה״כ:',
    'cartModal.continue': 'המשך להזמנה',
    'cartModal.maxItems': 'מקסימום 6 יחידות לפריט',
    'cartModal.orderNumber': 'מספר הזמנה',
    
    // Checkout Form
    'checkoutForm.back': 'חזרה לעגלה',
    'checkoutForm.loginRequired': 'נדרשת התחברות',
    'checkoutForm.loginRequiredDesc': 'כדי להשלים את ההזמנה, יש להתחבר או להירשם. הפרטים שלך יישמרו להזמנות הבאות!',
    'checkoutForm.loginSignup': 'התחברות / הרשמה',
    'checkoutForm.connectedAs': 'מחובר כ:',
    'checkoutForm.orderDetails': 'פרטי הזמנה',
    'checkoutForm.fullName': 'שם מלא',
    'checkoutForm.namePlaceholder': 'ישראל ישראלי',
    'checkoutForm.email': 'מייל',
    'checkoutForm.phone': 'טלפון',
    'checkoutForm.city': 'עיר',
    'checkoutForm.cityPlaceholder': 'תל אביב',
    'checkoutForm.address': 'כתובת',
    'checkoutForm.addressPlaceholder': 'רחוב הרצל 1',
    'checkoutForm.notes': 'הערות למשלוח (אופציונלי, עד 500 תווים)',
    'checkoutForm.notesPlaceholder': 'קומה, דירה, הוראות מיוחדות...',
    'checkoutForm.totalPayment': 'סה״כ לתשלום:',
    'checkoutForm.cashPayment': '💵 תשלום במזומן בעת המשלוח',
    'checkoutForm.orderCash': 'להזמין במזומן',
    'checkoutForm.sending': 'שולח...',
    'checkoutForm.confirmationSent': 'נשלח אישור למייל ולוואטסאפ',
    'checkoutForm.tooManyOrders': 'יותר מדי הזמנות. נסו שוב מאוחר יותר.',
    'checkoutForm.orderSuccess': 'ההזמנה נשלחה בהצלחה! נשלח מייל ווואטסאפ',
    'checkoutForm.orderError': 'שגיאה בשליחת ההזמנה, נסו שוב',
    
    // Order History
    'orderHistory.title': 'היסטוריית הזמנות',
    'orderHistory.myOrders': 'ההזמנות שלי',
    'orderHistory.subtitle': 'צפייה והזמנה חוזרת של הזמנות קודמות',
    'orderHistory.loginPrompt': 'התחברו כדי לראות את ההזמנות הקודמות',
    'orderHistory.login': 'התחברות',
    'orderHistory.loading': 'טוען הזמנות...',
    'orderHistory.noOrders': 'אין הזמנות קודמות',
    'orderHistory.ordersWillAppear': 'ההזמנות שלכם יופיעו כאן',
    'orderHistory.reorder': 'הזמנה חוזרת',
    'orderHistory.itemsAdded': 'הפריטים נוספו לעגלה!',
    'orderHistory.pending': 'ממתין לאישור',
    'orderHistory.confirmed': 'אושר',
    'orderHistory.preparing': 'בהכנה',
    'orderHistory.delivering': 'במשלוח',
    'orderHistory.completed': 'הושלם',
    'orderHistory.cancelled': 'בוטל',
    
    // Edit Profile Modal
    'editProfile.title': 'עריכת פרופיל',
    'editProfile.clickToChange': 'לחץ להחלפת תמונה',
    'editProfile.imageOnly': 'יש להעלות קובץ תמונה בלבד',
    'editProfile.maxSize': 'גודל התמונה מקסימלי 2MB',
    'editProfile.uploadSuccess': 'התמונה הועלתה בהצלחה!',
    'editProfile.uploadError': 'שגיאה בהעלאת התמונה',
    'editProfile.emailLabel': 'אימייל',
    'editProfile.fullNameLabel': 'שם מלא',
    'editProfile.namePlaceholder': 'השם שלך',
    'editProfile.phoneLabel': 'טלפון *',
    'editProfile.phonePlaceholder': '054-1234567',
    'editProfile.cityLabel': 'עיר',
    'editProfile.cityPlaceholder': 'שם העיר',
    'editProfile.addressLabel': 'כתובת',
    'editProfile.addressPlaceholder': 'רחוב ומספר בית',
    'editProfile.notesLabel': 'הערות למשלוח',
    'editProfile.notesPlaceholder': 'קוד בניין, קומה, הוראות מיוחדות...',
    'editProfile.save': 'שמור שינויים',
    'editProfile.saving': 'שומר...',
    'editProfile.success': 'הפרופיל עודכן בהצלחה! ✨',
    'editProfile.deleteAccount': 'מחיקת חשבון',
    
    // Change Password Modal
    'changePassword.title': 'שינוי סיסמה',
    'changePassword.currentPassword': 'סיסמה נוכחית',
    'changePassword.currentPlaceholder': 'הזן סיסמה נוכחית',
    'changePassword.newPassword': 'סיסמה חדשה',
    'changePassword.newPlaceholder': 'לפחות 8 תווים',
    'changePassword.confirmPassword': 'אימות סיסמה',
    'changePassword.confirmPlaceholder': 'הזן שוב את הסיסמה',
    'changePassword.requirements': 'אות גדולה + מספר + 8 תווים לפחות',
    'changePassword.change': 'שנה סיסמה',
    'changePassword.changing': 'מעדכן...',
    'changePassword.success': 'הסיסמה שונתה בהצלחה!',
    'changePassword.successDesc': 'השתמש בסיסמה החדשה בהתחברות הבאה',
    'changePassword.wrongCurrent': 'סיסמה נוכחית שגויה',
    'changePassword.noUser': 'לא נמצא משתמש מחובר',
    
    // Delete Account Modal
    'deleteAccount.title': 'מחיקת חשבון',
    'deleteAccount.typeConfirm': 'כדי להמשיך, הקלד',
    'deleteAccount.deleteWord': 'מחיקה',
    'deleteAccount.typePlaceholder': 'הקלד מחיקה',
    'deleteAccount.warning': 'פעולה זו תמחק לצמיתות את החשבון שלך וכל המידע הקשור אליו, כולל:',
    'deleteAccount.profileData': 'פרטי הפרופיל',
    'deleteAccount.orderHistory': 'היסטוריית הזמנות',
    'deleteAccount.noRecover': 'לא ניתן לשחזר את המידע לאחר המחיקה!',
    'deleteAccount.sendCode': 'נשלח קוד אימות למייל',
    'deleteAccount.continue': 'המשך',
    'deleteAccount.continueDelete': 'המשך למחיקה',
    'deleteAccount.sendingCode': 'שולח קוד...',
    'deleteAccount.enterCode': 'הזן את קוד האימות שנשלח למייל שלך:',
    'deleteAccount.enter6Digits': 'יש להזין 6 ספרות',
    'deleteAccount.resendIn': 'שלח שוב בעוד {seconds} שניות',
    'deleteAccount.resend': 'שלח קוד חדש',
    'deleteAccount.back': 'חזור',
    'deleteAccount.cancel': 'ביטול',
    'deleteAccount.deleting': 'מוחק...',
    'deleteAccount.deletePermanently': 'מחק לצמיתות',
    'deleteAccount.deleted': 'החשבון נמחק',
    'deleteAccount.goodbye': 'להתראות, תמיד אפשר לחזור 🍪',
    'deleteAccount.noEmail': 'לא נמצא אימייל משתמש',
    'deleteAccount.codeSent': 'קוד נשלח! 📧',
    'deleteAccount.checkEmail': 'בדוק את תיבת המייל שלך',
    
    // Cookie Card
    'cookieCard.added': 'נוסף!',
    'cookieCard.add': 'הוסף',
    'cookieCard.addToCart': 'הוסף לעגלה',
    'cookieCard.recommended': 'מומלץ',
    'cookieCard.new': 'חדש',
    'cookieCard.maxItems': 'מקסימום 6 יחידות לפריט',
    'cookieCard.readMore': 'קרא עוד על',
    
    // UI Labels
    'ui.infoBanner': 'באנר מידע',
    'ui.socialMedia': 'רשתות חברתיות',
    'ui.boutiqueSubtitle': 'עוגיות בוטיק בעבודת יד · טעמים שלא תשכחו',
    'ui.brandName': 'מזון האושר',
    'ui.greeting.morning': 'בוקר טוב',
    'ui.greeting.afternoon': 'צהריים טובים',
    'ui.greeting.evening': 'ערב טוב',
    'ui.greeting.night': 'לילה טוב',
    'ui.boutiqueShort': 'עוגיות בוטיק בעבודת יד',
    'ui.loading': 'טוען...',
    'notFound.connecting': 'מתחבר...',
    'notFound.metaTitle': '404 | הדף לא נמצא — מזון האושר',
    'notFound.metaDescription': 'הדף שחיפשת לא נמצא. חזור לדף הבית של מזון האושר ליהנות מעוגיות אמריקאיות בעבודת יד.',
    'notFound.title': 'אופס! העוגייה הזו נאכלה',
    'notFound.subtitle': 'הדף שחיפשת לא קיים, אבל יש לנו המון עוגיות טריות בדף הבית',
    'notFound.home': 'חזרה לדף הבית',
    'notFound.back': 'חזור אחורה',
    'notFound.requestedPath': 'נתיב מבוקש:',
    'ui.skipToContent': 'דלג לתוכן הראשי',
    'ui.displayMode': 'מצב תצוגה',
    'ui.themeLight': 'בהיר',
    'ui.themeDark': 'כהה',
    'ui.themeAuto': 'אוטומטי',
    'ui.a11yMenu': 'תפריט נגישות',
    'ui.a11yClose': 'סגור תפריט נגישות',
    'ui.a11yContent': 'תוכן',
    'ui.a11yFontSize': 'גודל טקסט',
    'ui.a11yLineHeight': 'גובה שורה',
    'ui.a11yTextAlign': 'יישור טקסט',
    'ui.a11yDisplay': 'תצוגה',
    'ui.a11yNavigation': 'ניווט וקריאה',
    'ui.a11yHighContrast': 'ניגודיות גבוהה',
    'ui.a11yInvertColors': 'היפוך צבעים',
    'ui.a11yHighlightLinks': 'הדגשת קישורים',
    'ui.a11yHighlightTitles': 'הדגשת כותרות',
    'ui.a11yHideImages': 'הסתרת תמונות',
    'ui.a11yBigCursor': 'סמן גדול',
    'ui.a11yReadingGuide': 'מדריך קריאה',
    'ui.a11yReduceMotion': 'ביטול אנימציות',
    'ui.a11yReadableFont': 'פונט קריא',
    'ui.a11yTextSpacing': 'ריווח טקסט',
    'ui.a11yHighlightFocus': 'הדגשת פוקוס',
    'ui.a11yReset': 'איפוס כל ההגדרות',
    'ui.a11yFontNormal': 'רגיל',
    'ui.a11yFontLarge': 'גדול',
    'ui.a11yFontLarger': 'גדול+',
    'ui.a11yFontHuge': 'ענק',
    'ui.a11yLineNormal': 'רגיל',
    'ui.a11yLineLarge': 'גדול',
    'ui.a11yLineXL': 'XL',
    'ui.a11ySatNormal': 'רגיל',
    'ui.a11ySatLow': 'רוויה נמוכה',
    'ui.a11ySatGray': 'גווני אפור',
    'ui.a11yAlignDefault': 'ברירת מחדל',
    'ui.a11yAlignRight': 'ימין',
    'ui.a11yAlignCenter': 'מרכז',
    'ui.a11yAlignLeft': 'שמאל',
    // Auth Modal
    'auth.loginTitle': 'התחברות',
    'auth.registerTitle': 'הרשמה',
    'auth.forgotTitle': 'שכחתי סיסמה',
    'auth.otpTitle': 'אימות דו-שלבי',
    'auth.smsLoginTitle': 'התחברות ב-SMS',
    'auth.smsOtpTitle': 'אימות SMS',
    'auth.smsLoginDesc': 'הזן את מספר הטלפון שלך ונשלח לך קוד אימות ב-SMS',
    'auth.phoneLabel': 'מספר טלפון *',
    'auth.sendCode': 'שלח קוד אימות',
    'auth.sending': 'שולח...',
    'auth.backToLogin': 'חזרה להתחברות רגילה',
    'auth.codeSentTo': 'שלחנו קוד אימות בן 6 ספרות ל-',
    'auth.verifying': 'מאמת...',
    'auth.verify': 'אמת',
    'auth.resendIn': 'שלח שוב בעוד {seconds} שניות',
    'auth.resendCode': 'שלח קוד חדש',
    'auth.back': 'חזרה',
    'auth.rememberDevice': 'זכור את המכשיר הזה',
    'auth.verifyAndContinue': 'אמת והמשך',
    'auth.smsLogin': 'התחברות ב-SMS',
    'auth.or': 'או',
    'auth.fullNameLabel': 'שם מלא *',
    'auth.fullNamePlaceholder': 'ישראל ישראלי',
    'auth.phoneOptional': 'טלפון',
    'auth.emailLabel': 'אימייל *',
    'auth.passwordLabel': 'סיסמה *',
    'auth.passwordPlaceholder': 'לפחות 6 תווים',
    'auth.forgotPassword': 'שכחתי סיסמה',
    'auth.loggingIn': 'מתחבר...',
    'auth.registering': 'נרשם...',
    'auth.sendingReset': 'שולח...',
    'auth.loginBtn': 'התחברות',
    'auth.registerBtn': 'הרשמה',
    'auth.sendResetLink': 'שלח קישור לאיפוס',
    'auth.backToLoginLink': 'חזרה להתחברות',
    'auth.noAccount': 'אין לך חשבון?',
    'auth.hasAccount': 'כבר יש לך חשבון?',
    'auth.signupLink': 'הירשם',
    'auth.loginLink': 'התחבר',
    'auth.tooManyAttempts': 'יותר מדי ניסיונות שגויים. נסה שוב בעוד {minutes} דקות',
    'auth.wrongCode': 'קוד אימות שגוי',
    'auth.attemptsLeft': 'נותרו {count} ניסיונות',
    'auth.enter6Digits': 'יש להזין 6 ספרות',
    'auth.invalidPhone': 'מספר טלפון לא תקין',
    'auth.phoneTooLong': 'מספר טלפון ארוך מדי',
    'auth.israeliPhoneRequired': 'יש להזין מספר טלפון נייד ישראלי תקין',
    'auth.invalidEmail': 'כתובת אימייל לא תקינה',
    'auth.passwordMin': 'סיסמה חייבת להכיל לפחות 6 תווים',
    'auth.nameMin': 'שם חייב להכיל לפחות 2 תווים',
    'auth.nameTooLong': 'שם ארוך מדי',
    'auth.codeSentEmail': 'קוד נשלח! 📧',
    'auth.checkEmailInbox': 'בדוק את תיבת המייל שלך',
    'auth.codeSentSms': 'קוד נשלח! 📱',
    'auth.checkSms': 'בדוק את הודעות ה-SMS שלך',
    'auth.resetSent': 'נשלח בהצלחה! 📧',
    'auth.resetSentDesc': 'קישור לאיפוס סיסמה נשלח לאימייל שלך',
    'auth.wrongCredentials': 'אימייל או סיסמה שגויים',
    'auth.emailExists': 'כתובת האימייל כבר רשומה במערכת',
    'auth.cancelledLogin': 'ההתחברות בוטלה',
    'auth.popupClosed': 'החלון נסגר לפני השלמת ההתחברות',
    'auth.networkError': 'שגיאת רשת, בדוק את החיבור לאינטרנט',
    'auth.providerNotEnabled': 'ספק ההתחברות לא מוגדר כרגע',
    'auth.unknownDevice': 'מכשיר לא ידוע',
    'auth.error': 'שגיאה',
    'auth.genericError': 'אירעה שגיאה, נסו שוב',
    'auth.sendCodeError': 'אירעה שגיאה בשליחת הקוד',
    'auth.sessionError': 'שגיאה בהתחברות',
    
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.cookies': 'Cookies',
    'nav.about': 'About',
    'nav.reviews': 'Reviews',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.orderHistory': 'Order History',
    'nav.editProfile': 'Edit Profile',
    
    // Hero
    'hero.title': 'MazonHaosher',
    'hero.subtitle': 'Giant American Cookies',
    'hero.description': 'Handcrafted giant American cookies made from the finest ingredients',
    'hero.cta': 'View Our Cookies',
    'hero.madeWithLove': 'Made with Love',
    'hero.viewMenu': 'View Menu',
    
    // Cookies Section
    'cookies.title': 'Our Collection',
    'cookies.subtitle': 'Made with love, especially for you ✨',
    'cookies.addToCart': 'Add to Cart',
    'cookies.outOfStock': 'Out of Stock',
    'cookies.price': '₪',
    'cookies.search': 'Search...',
    'cookies.all': 'All',
    'cookies.chocolate': 'Chocolate',
    'cookies.fruits': 'Fruits',
    'cookies.candy': 'Candy',
    'cookies.nuts': 'Nuts',
    'cookies.classic': 'Classic',
    'cookies.recommended': 'Recommended',
    'cookies.new': 'New',
    'cookies.favorites': 'Favorites',
    'cookies.sortDefault': 'Default',
    'cookies.sortName': 'By Name',
    'cookies.sortPrice': 'By Price',
    'cookies.noResults': 'No cookies found',
    'cookies.clearFilters': 'Clear filters',
    
    // Cookie names
    'cookie.lotus': 'Lotus',
    'cookie.kinder': 'Kinder',
    'cookie.kinderBueno': 'Kinder Bueno',
    'cookie.redVelvet': 'Red Velvet',
    'cookie.confetti': 'Confetti',
    'cookie.pistachio': 'Pistachio',
    'cookie.pretzel': 'Pretzel',
    'cookie.chocolateChip': 'Chocolate Chip',
    'cookie.oreo': 'Oreo',
    'cookie.peanutButter': 'Peanut Butter',
    'cookie.lemon': 'Lemon',
    'cookie.macadamia': 'Macadamia',
    'cookie.oatmeal': 'Oatmeal',
    'cookie.saltedCaramel': 'Salted Caramel',
    'cookie.tahini': 'Tahini',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'Lotus biscuit and caramel spread',
    'cookie.kinderDesc': 'Kinder chocolate with colorful chocolate balls',
    'cookie.kinderBuenoDesc': 'Kinder Bueno, milk chocolate and chocolate coating',
    'cookie.redVelvetDesc': 'Red velvet dough, white chocolate and raspberry crumbs',
    'cookie.confettiDesc': 'Colorful sprinkles and Smarties',
    'cookie.pistachioDesc': 'White chocolate, roasted pistachios and pomegranate seeds',
    'cookie.pretzelDesc': 'Salted pretzel, white chocolate and chocolate chips',
    'cookie.chocolateChipDesc': 'Belgian dark and milk chocolate chips',
    'cookie.oreoDesc': 'Oreo crumbs, white chocolate and vanilla cream',
    'cookie.peanutButterDesc': 'Peanut butter, roasted peanuts and chocolate',
    'cookie.lemonDesc': 'Fresh lemon zest with sugar coating',
    'cookie.macadamiaDesc': 'Macadamia nuts and white chocolate',
    'cookie.oatmealDesc': 'Oatmeal, raisins and cinnamon',
    'cookie.saltedCaramelDesc': 'Homemade caramel with sea salt crystals',
    'cookie.tahiniDesc': 'Raw tahini, sesame seeds and honey',
    
    // Cookie of the Week
    'cotw.title': 'Cookie of the Week',
    'cotw.discount': 'OFF',
    'cotw.originalPrice': 'Original Price',
    'cotw.salePrice': 'Sale Price',
    
    // About
    'about.title': 'About MazonHaosher',
    'about.ourStory': 'Our Story',
    'about.headline': 'Creating happiness, one creation at a time',
    'about.description': 'Mazon HaOsher started in a small home kitchen with a simple dream: to share the warmth and comfort of homemade baked goods with our community.',
    'about.madeWithLove': 'Made with Love',
    'about.madeWithLoveDesc': 'Every batch is prepared with care and passion, just like grandma used to make.',
    'about.freshIngredients': 'Fresh Ingredients',
    'about.freshIngredientsDesc': 'We use only the freshest and finest ingredients.',
    'about.dailyPrep': 'Daily Preparation',
    'about.dailyPrepDesc': 'Our products are freshly prepared every morning for perfect taste.',
    
    // Reviews
    'reviews.title': 'What Our Customers Say',
    'reviews.subtitle': 'Reviews from happy customers',
    'reviews.addReview': 'Add a Review',
    'reviews.selectProduct': 'Select a product',
    'reviews.selectProductPlaceholder': 'Select a product...',
    'reviews.rating': 'Rating',
    'reviews.yourReview': 'Your review (optional, up to 500 characters)',
    'reviews.reviewPlaceholder': 'Tell us what you thought...',
    'reviews.submit': 'Submit Review',
    'reviews.submitting': 'Submitting...',
    'reviews.loginRequired': 'You need to log in to write a review',
    'reviews.recentReviews': 'Recent Reviews',
    'reviews.filterAll': 'All Products',
    'reviews.noReviews': 'No reviews yet. Be the first to write a review!',
    'reviews.thankYou': 'Thanks for your review! 🍪',
    'reviews.reviewAdded': 'Your review has been added successfully',
    'reviews.reviewsCount': 'reviews',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': "Here you'll find answers to the most common questions. Didn't find what you're looking for? Contact us!",
    'faq.delivery': 'How does delivery work?',
    'faq.deliveryAnswer': 'Deliveries are made Sunday-Thursday, 10:00-20:00. Shipping costs ₪25 nationwide, free shipping on orders over ₪150. Delivery time is 1-3 business days.',
    'faq.payment': 'What payment methods do you accept?',
    'faq.paymentAnswer': 'Currently we accept cash payment upon delivery only. Credit card payment will be added soon.',
    'faq.freshness': 'How long do the products stay fresh?',
    'faq.freshnessAnswer': 'Our products are freshly made for each order and stay fresh for up to 5 days at room temperature or up to two weeks in the refrigerator. We recommend heating in the microwave for 10 seconds for the perfect experience!',
    'faq.allergens': 'What about allergens?',
    'faq.allergensAnswer': 'All our cookies contain gluten, dairy and eggs. Some cookies contain nuts, peanuts or soy. If you have a specific allergy, please note it in your order and we will accommodate you.',
    'faq.events': 'Can I order for events?',
    'faq.eventsAnswer': 'Absolutely! We offer special packages for events, birthdays, weddings and bar/bat mitzvahs. Contact us for a personalized quote.',
    'faq.contact': 'How can I contact you?',
    'faq.contactAnswer': 'You can contact us via WhatsApp using the floating button below, through the website form, or by phone at 054-6791198. We are available Sunday-Thursday between 9:00-21:00.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.address': '39 Kadesh Blvd, Ashkelon',
    'contact.phone': '054-679-1198',
    'contact.hours': 'Delivery within 3 business days',
    
    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.free': 'Free',
    
    // Checkout
    'checkout.title': 'Order Details',
    'checkout.name': 'Full Name',
    'checkout.phone': 'Phone',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.notes': 'Order Notes',
    'checkout.submit': 'Place Order',
    'checkout.success': 'Order placed successfully!',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.orContinueWith': 'Or continue with',
    'auth.phoneLogin': 'Login with Phone',
    'auth.verifyCode': 'Verify Code',
    'auth.loginTitle': 'Login',
    'auth.registerTitle': 'Sign Up',
    'auth.forgotTitle': 'Forgot Password',
    'auth.otpTitle': 'Two-Factor Auth',
    'auth.smsLoginTitle': 'SMS Login',
    'auth.smsOtpTitle': 'SMS Verification',
    'auth.smsLoginDesc': 'Enter your phone number and we will send you a verification code via SMS',
    'auth.phoneLabel': 'Phone Number *',
    'auth.sendCode': 'Send Code',
    'auth.sending': 'Sending...',
    'auth.backToLogin': 'Back to regular login',
    'auth.codeSentTo': 'We sent a 6-digit verification code to',
    'auth.verifying': 'Verifying...',
    'auth.verify': 'Verify',
    'auth.resendIn': 'Resend in {seconds} seconds',
    'auth.resendCode': 'Send new code',
    'auth.back': 'Back',
    'auth.rememberDevice': 'Remember this device',
    'auth.verifyAndContinue': 'Verify and continue',
    'auth.smsLogin': 'SMS Login',
    'auth.or': 'or',
    'auth.fullNameLabel': 'Full Name *',
    'auth.fullNamePlaceholder': 'John Doe',
    'auth.phoneOptional': 'Phone',
    'auth.emailLabel': 'Email *',
    'auth.passwordLabel': 'Password *',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Signing up...',
    'auth.sendingReset': 'Sending...',
    'auth.loginBtn': 'Login',
    'auth.registerBtn': 'Sign Up',
    'auth.sendResetLink': 'Send reset link',
    'auth.backToLoginLink': 'Back to login',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signupLink': 'Sign up',
    'auth.loginLink': 'Log in',
    'auth.loginButton': 'Log In',
    'auth.signupButton': 'Sign Up',
    'auth.tooManyAttempts': 'Too many failed attempts. Try again in {minutes} minutes',
    'auth.wrongCode': 'Invalid verification code',
    'auth.attemptsLeft': '{count} attempts remaining',
    'auth.enter6Digits': 'Please enter 6 digits',
    'auth.invalidPhone': 'Invalid phone number',
    'auth.phoneTooLong': 'Phone number too long',
    'auth.israeliPhoneRequired': 'Please enter a valid Israeli mobile number',
    'auth.invalidEmail': 'Invalid email address',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.nameMin': 'Name must be at least 2 characters',
    'auth.nameTooLong': 'Name is too long',
    'auth.codeSentEmail': 'Code sent! 📧',
    'auth.checkEmailInbox': 'Check your email inbox',
    'auth.codeSentSms': 'Code sent! 📱',
    'auth.checkSms': 'Check your SMS messages',
    'auth.resetSent': 'Sent successfully! 📧',
    'auth.resetSentDesc': 'A password reset link was sent to your email',
    'auth.wrongCredentials': 'Invalid email or password',
    'auth.emailExists': 'This email is already registered',
    'auth.cancelledLogin': 'Login was cancelled',
    'auth.popupClosed': 'The window was closed before completing login',
    'auth.networkError': 'Network error, check your internet connection',
    'auth.providerNotEnabled': 'This login provider is not currently configured',
    'auth.unknownDevice': 'Unknown device',
    'auth.error': 'Error',
    'auth.genericError': 'An error occurred, please try again',
    'auth.sendCodeError': 'An error occurred while sending the code',
    'auth.sessionError': 'Login error',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.deleteAccount': 'Delete Account',
    'profile.changePassword': 'Change Password',
    
    // Newsletter
    'newsletter.title': "Don't Miss Out!",
    'newsletter.subtitle': 'Subscribe to our newsletter for special offers',
    'newsletter.emailPlaceholder': 'Your email address',
    'newsletter.phonePlaceholder': 'Phone number (optional)',
    'newsletter.button': 'Subscribe for updates ✨',
    'newsletter.submitting': 'Submitting...',
    'newsletter.success': 'Subscribed successfully! 🎉',
    'newsletter.successDesc': "You'll receive updates on deals and news",
    'newsletter.thankYou': 'Thanks for subscribing! ✨',
    'newsletter.thankYouDesc': "We'll update you on special deals, new products and sweet surprises",
    'newsletter.noSpam': "We promise not to send spam. Only delicious updates. ✨",
    
    // Footer
    'footer.rights': 'All Rights Reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.close': 'Close',
    'general.back': 'Back',
    'general.next': 'Next',
    'general.confirm': 'Confirm',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    
    // Gift Package
    'gift.title': 'Gift Packages',
    'gift.subtitle': 'Build the perfect gift package with your favorite cookies',
    'gift.selectCookies': 'Select cookies for the package',
    'gift.packageName': 'Package Name',
    'gift.packageNameOptional': 'Package name (optional)',
    'gift.packageNamePlaceholder': 'e.g., Birthday gift',
    'gift.addToCart': 'Add to Cart',
    'gift.small': 'Small Package',
    'gift.medium': 'Medium Package',
    'gift.large': 'Large Package',
    'gift.smallDesc': '6 cookies of your choice',
    'gift.mediumDesc': '12 cookies of your choice',
    'gift.largeDesc': '24 cookies of your choice',
    'gift.discount': 'OFF',
    'gift.selected': 'Selected',
    'gift.outOf': 'out of',
    'gift.moreToSelect': '{count} more to select',
    'gift.packageFull': 'Package complete!',
    'gift.packageFullError': 'Package is full',
    'gift.alreadySelected': 'You already selected {count} cookies',
    'gift.yourCookies': 'Your selected cookies',
    'gift.regularPrice': 'Regular price:',
    'gift.packageDiscount': 'Package discount',
    'gift.total': 'Total:',
    'gift.notComplete': 'Package not complete',
    'gift.selectMore': 'Please select {count} more cookies',
    'gift.addedToCart': 'Package added to cart! 🎁',
    'gift.cookies': 'cookies',
    
    // Cookie of the Week
    'cotw.badge': 'Cookie of the Week',
    'cotw.add': 'Add',
    
    // Cart Modal
    'cartModal.title': 'My Cart',
    'cartModal.completing': 'Complete Order',
    'cartModal.empty': 'Cart is empty',
    'cartModal.addCookies': 'Add some delicious cookies!',
    'cartModal.cookies': 'cookies',
    'cartModal.saved': 'You saved',
    'cartModal.total': 'Total:',
    'cartModal.continue': 'Continue to Order',
    'cartModal.maxItems': 'Maximum 6 items per product',
    'cartModal.orderNumber': 'Order number',
    
    // Checkout Form
    'checkoutForm.back': 'Back to cart',
    'checkoutForm.loginRequired': 'Login Required',
    'checkoutForm.loginRequiredDesc': 'To complete your order, please login or sign up. Your details will be saved for future orders!',
    'checkoutForm.loginSignup': 'Login / Sign Up',
    'checkoutForm.connectedAs': 'Connected as:',
    'checkoutForm.orderDetails': 'Order Details',
    'checkoutForm.fullName': 'Full Name',
    'checkoutForm.namePlaceholder': 'John Doe',
    'checkoutForm.email': 'Email',
    'checkoutForm.phone': 'Phone',
    'checkoutForm.city': 'City',
    'checkoutForm.cityPlaceholder': 'Tel Aviv',
    'checkoutForm.address': 'Address',
    'checkoutForm.addressPlaceholder': '1 Herzl St',
    'checkoutForm.notes': 'Delivery notes (optional, up to 500 characters)',
    'checkoutForm.notesPlaceholder': 'Floor, apartment, special instructions...',
    'checkoutForm.totalPayment': 'Total to pay:',
    'checkoutForm.cashPayment': '💵 Cash payment upon delivery',
    'checkoutForm.orderCash': 'Order with Cash',
    'checkoutForm.sending': 'Sending...',
    'checkoutForm.confirmationSent': 'Confirmation sent via email and WhatsApp',
    'checkoutForm.tooManyOrders': 'Too many orders. Try again later.',
    'checkoutForm.orderSuccess': 'Order sent successfully! Email and WhatsApp sent',
    'checkoutForm.orderError': 'Error sending order, please try again',
    
    // Order History
    'orderHistory.title': 'Order History',
    'orderHistory.myOrders': 'My Orders',
    'orderHistory.subtitle': 'View and reorder previous orders',
    'orderHistory.loginPrompt': 'Login to see your previous orders',
    'orderHistory.login': 'Login',
    'orderHistory.loading': 'Loading orders...',
    'orderHistory.noOrders': 'No previous orders',
    'orderHistory.ordersWillAppear': 'Your orders will appear here',
    'orderHistory.reorder': 'Reorder',
    'orderHistory.itemsAdded': 'Items added to cart!',
    'orderHistory.pending': 'Pending',
    'orderHistory.confirmed': 'Confirmed',
    'orderHistory.preparing': 'Preparing',
    'orderHistory.delivering': 'Delivering',
    'orderHistory.completed': 'Completed',
    'orderHistory.cancelled': 'Cancelled',
    
    // Edit Profile Modal
    'editProfile.title': 'Edit Profile',
    'editProfile.clickToChange': 'Click to change photo',
    'editProfile.imageOnly': 'Please upload an image file only',
    'editProfile.maxSize': 'Maximum image size is 2MB',
    'editProfile.uploadSuccess': 'Image uploaded successfully!',
    'editProfile.uploadError': 'Error uploading image',
    'editProfile.emailLabel': 'Email',
    'editProfile.fullNameLabel': 'Full Name',
    'editProfile.namePlaceholder': 'Your name',
    'editProfile.phoneLabel': 'Phone *',
    'editProfile.phonePlaceholder': '054-1234567',
    'editProfile.cityLabel': 'City',
    'editProfile.cityPlaceholder': 'City name',
    'editProfile.addressLabel': 'Address',
    'editProfile.addressPlaceholder': 'Street and house number',
    'editProfile.notesLabel': 'Delivery notes',
    'editProfile.notesPlaceholder': 'Building code, floor, special instructions...',
    'editProfile.save': 'Save Changes',
    'editProfile.saving': 'Saving...',
    'editProfile.success': 'Profile updated successfully! ✨',
    'editProfile.deleteAccount': 'Delete Account',
    
    // Change Password Modal
    'changePassword.title': 'Change Password',
    'changePassword.currentPassword': 'Current Password',
    'changePassword.currentPlaceholder': 'Enter current password',
    'changePassword.newPassword': 'New Password',
    'changePassword.newPlaceholder': 'At least 8 characters',
    'changePassword.confirmPassword': 'Confirm Password',
    'changePassword.confirmPlaceholder': 'Enter password again',
    'changePassword.requirements': 'Uppercase letter + number + at least 8 characters',
    'changePassword.change': 'Change Password',
    'changePassword.changing': 'Updating...',
    'changePassword.success': 'Password changed successfully!',
    'changePassword.successDesc': 'Use your new password on next login',
    'changePassword.wrongCurrent': 'Current password is incorrect',
    'changePassword.noUser': 'No logged in user found',
    
    // Delete Account Modal
    'deleteAccount.title': 'Delete Account',
    'deleteAccount.typeConfirm': 'To continue, type',
    'deleteAccount.deleteWord': 'delete',
    'deleteAccount.typePlaceholder': 'Type delete',
    'deleteAccount.warning': 'This action will permanently delete your account and all associated data, including:',
    'deleteAccount.profileData': 'Profile data',
    'deleteAccount.orderHistory': 'Order history',
    'deleteAccount.noRecover': 'Data cannot be recovered after deletion!',
    'deleteAccount.sendCode': 'A verification code will be sent to email',
    'deleteAccount.continue': 'Continue',
    'deleteAccount.continueDelete': 'Continue to delete',
    'deleteAccount.sendingCode': 'Sending code...',
    'deleteAccount.enterCode': 'Enter the verification code sent to your email:',
    'deleteAccount.enter6Digits': 'Please enter 6 digits',
    'deleteAccount.resendIn': 'Resend in {seconds} seconds',
    'deleteAccount.resend': 'Send new code',
    'deleteAccount.back': 'Back',
    'deleteAccount.cancel': 'Cancel',
    'deleteAccount.deleting': 'Deleting...',
    'deleteAccount.deletePermanently': 'Delete permanently',
    'deleteAccount.deleted': 'Account deleted',
    'deleteAccount.goodbye': 'Goodbye, you can always come back 🍪',
    'deleteAccount.noEmail': 'No user email found',
    'deleteAccount.codeSent': 'Code sent! 📧',
    'deleteAccount.checkEmail': 'Check your email inbox',
    
    // Cookie Card
    'cookieCard.added': 'Added!',
    'cookieCard.add': 'Add',
    'cookieCard.addToCart': 'Add to Cart',
    'cookieCard.recommended': 'Recommended',
    'cookieCard.new': 'New',
    'cookieCard.maxItems': 'Maximum 6 items per product',
    'cookieCard.readMore': 'Read more about',
    
    // UI Labels
    'ui.infoBanner': 'Info banner',
    'ui.socialMedia': 'Social media',
    'ui.boutiqueSubtitle': "Handcrafted boutique cookies · Flavors you won't forget",
    'ui.brandName': 'Mazon HaOsher',
    'ui.greeting.morning': 'Good morning',
    'ui.greeting.afternoon': 'Good afternoon',
    'ui.greeting.evening': 'Good evening',
    'ui.greeting.night': 'Good night',
    'ui.boutiqueShort': 'Handcrafted Boutique Cookies',
    'ui.loading': 'Loading...',
    'notFound.connecting': 'Connecting...',
    'notFound.metaTitle': '404 | Page Not Found — Mazon HaOsher',
    'notFound.metaDescription': 'The page you are looking for does not exist. Return to the Mazon HaOsher home page to enjoy handmade American cookies.',
    'notFound.title': 'Oops! This cookie has been eaten',
    'notFound.subtitle': "The page you are looking for doesn't exist, but we have plenty of fresh cookies on the home page",
    'notFound.home': 'Back to home',
    'notFound.back': 'Go back',
    'notFound.requestedPath': 'Requested path:',
    'ui.skipToContent': 'Skip to main content',
    'ui.displayMode': 'Display mode',
    'ui.themeLight': 'Light',
    'ui.themeDark': 'Dark',
    'ui.themeAuto': 'Auto',
    'ui.a11yMenu': 'Accessibility Menu',
    'ui.a11yClose': 'Close accessibility menu',
    'ui.a11yContent': 'Content',
    'ui.a11yFontSize': 'Font Size',
    'ui.a11yLineHeight': 'Line Height',
    'ui.a11yTextAlign': 'Text Align',
    'ui.a11yDisplay': 'Display',
    'ui.a11yNavigation': 'Navigation & Reading',
    'ui.a11yHighContrast': 'High Contrast',
    'ui.a11yInvertColors': 'Invert Colors',
    'ui.a11yHighlightLinks': 'Highlight Links',
    'ui.a11yHighlightTitles': 'Highlight Titles',
    'ui.a11yHideImages': 'Hide Images',
    'ui.a11yBigCursor': 'Big Cursor',
    'ui.a11yReadingGuide': 'Reading Guide',
    'ui.a11yReduceMotion': 'Reduce Motion',
    'ui.a11yReadableFont': 'Readable Font',
    'ui.a11yTextSpacing': 'Text Spacing',
    'ui.a11yHighlightFocus': 'Highlight Focus',
    'ui.a11yReset': 'Reset All Settings',
    'ui.a11yFontNormal': 'Normal',
    'ui.a11yFontLarge': 'Large',
    'ui.a11yFontLarger': 'Larger',
    'ui.a11yFontHuge': 'Huge',
    'ui.a11yLineNormal': 'Normal',
    'ui.a11yLineLarge': 'Large',
    'ui.a11yLineXL': 'XL',
    'ui.a11ySatNormal': 'Normal',
    'ui.a11ySatLow': 'Low Sat.',
    'ui.a11ySatGray': 'Grayscale',
    'ui.a11yAlignDefault': 'Default',
    'ui.a11yAlignRight': 'Right',
    'ui.a11yAlignCenter': 'Center',
    'ui.a11yAlignLeft': 'Left',
  },
  ar: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.cookies': 'كوكيز',
    'nav.about': 'من نحن',
    'nav.reviews': 'تقييمات',
    'nav.faq': 'أسئلة شائعة',
    'nav.contact': 'اتصل بنا',
    'nav.cart': 'السلة',
    'nav.profile': 'الملف الشخصي',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.orderHistory': 'سجل الطلبات',
    'nav.editProfile': 'تعديل الملف',
    
    // Hero
    'hero.title': 'مزون السعادة',
    'hero.subtitle': 'كوكيز أمريكية عملاقة',
    'hero.description': 'كوكيز أمريكية عملاقة مصنوعة يدويًا من أجود المكونات',
    'hero.cta': 'عرض القائمة',
    'hero.madeWithLove': 'صُنع بحب',
    'hero.viewMenu': 'عرض القائمة',
    
    // Cookies Section
    'cookies.title': 'مجموعتنا',
    'cookies.subtitle': 'مصنوع بحب، خصيصًا لكم ✨',
    'cookies.addToCart': 'أضف للسلة',
    'cookies.outOfStock': 'نفد من المخزون',
    'cookies.price': '₪',
    'cookies.search': 'بحث...',
    'cookies.all': 'الكل',
    'cookies.chocolate': 'شوكولاتة',
    'cookies.fruits': 'فواكه',
    'cookies.candy': 'حلويات',
    'cookies.nuts': 'مكسرات',
    'cookies.classic': 'كلاسيكي',
    'cookies.recommended': 'موصى به',
    'cookies.new': 'جديد',
    'cookies.favorites': 'المفضلة',
    'cookies.sortDefault': 'افتراضي',
    'cookies.sortName': 'حسب الاسم',
    'cookies.sortPrice': 'حسب السعر',
    'cookies.noResults': 'لم يتم العثور على كوكيز',
    'cookies.clearFilters': 'مسح الفلاتر',
    
    // Cookie names
    'cookie.lotus': 'لوتس',
    'cookie.kinder': 'كيندر',
    'cookie.kinderBueno': 'كيندر بوينو',
    'cookie.redVelvet': 'ريد فلفت',
    'cookie.confetti': 'كونفيتي',
    'cookie.pistachio': 'فستق',
    'cookie.pretzel': 'بريتزل',
    'cookie.chocolateChip': 'شوكولاتة تشيبس',
    'cookie.oreo': 'أوريو',
    'cookie.peanutButter': 'زبدة الفول السوداني',
    'cookie.lemon': 'ليمون',
    'cookie.macadamia': 'مكاداميا',
    'cookie.oatmeal': 'شوفان',
    'cookie.saltedCaramel': 'كراميل مملح',
    'cookie.tahini': 'طحينة',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'بسكويت لوتس وكراميل',
    'cookie.kinderDesc': 'شوكولاتة كيندر مع كرات شوكولاتة ملونة',
    'cookie.kinderBuenoDesc': 'كيندر بوينو، شوكولاتة حليب وتغليفة شوكولاتة',
    'cookie.redVelvetDesc': 'عجينة ريد فلفت، شوكولاتة بيضاء وفتات التوت',
    'cookie.confettiDesc': 'رشات ملونة وسمارتيز',
    'cookie.pistachioDesc': 'شوكولاتة بيضاء، فستق محمص وبذور رمان',
    'cookie.pretzelDesc': 'بريتزل مملح، شوكولاتة بيضاء وتشيبس شوكولاتة',
    'cookie.chocolateChipDesc': 'تشيبس شوكولاتة بلجيكية داكنة وحليب',
    'cookie.oreoDesc': 'فتات أوريو، شوكولاتة بيضاء وكريمة فانيلا',
    'cookie.peanutButterDesc': 'زبدة فول سوداني، فول سوداني محمص وشوكولاتة',
    'cookie.lemonDesc': 'قشر ليمون طازج مع تغليفة سكر',
    'cookie.macadamiaDesc': 'مكسرات مكاداميا وشوكولاتة بيضاء',
    'cookie.oatmealDesc': 'شوفان، زبيب وقرفة',
    'cookie.saltedCaramelDesc': 'كراميل منزلي مع بلورات ملح البحر',
    'cookie.tahiniDesc': 'طحينة خام، سمسم وعسل',
    
    // Cookie of the Week
    'cotw.title': 'كوكيز الأسبوع',
    'cotw.discount': 'خصم',
    'cotw.originalPrice': 'السعر الأصلي',
    'cotw.salePrice': 'سعر العرض',
    'cotw.badge': 'كوكيز الأسبوع',
    'cotw.add': 'أضف',
    
    // About
    'about.title': 'عن مزون السعادة',
    'about.ourStory': 'قصتنا',
    'about.headline': 'نصنع السعادة، قطعة تلو الأخرى',
    'about.description': 'بدأ مزون السعادة في مطبخ منزلي صغير بحلم بسيط: مشاركة الدفء والراحة من المخبوزات المنزلية مع مجتمعنا.',
    'about.madeWithLove': 'صُنع بحب',
    'about.madeWithLoveDesc': 'كل دفعة محضرة بعناية وشغف، تمامًا كما كانت تصنعها الجدة.',
    'about.freshIngredients': 'مكونات طازجة',
    'about.freshIngredientsDesc': 'نستخدم فقط المكونات الأطزج والأجود.',
    'about.dailyPrep': 'تحضير يومي',
    'about.dailyPrepDesc': 'منتجاتنا تُحضر طازجة كل صباح لمذاق مثالي.',
    
    // Reviews
    'reviews.title': 'ماذا يقول عملاؤنا',
    'reviews.subtitle': 'تقييمات من عملاء سعداء',
    'reviews.addReview': 'أضف تقييم',
    'reviews.selectProduct': 'اختر منتج',
    'reviews.selectProductPlaceholder': 'اختر منتج...',
    'reviews.rating': 'التقييم',
    'reviews.yourReview': 'تقييمك (اختياري، حتى 500 حرف)',
    'reviews.reviewPlaceholder': 'أخبرنا رأيك...',
    'reviews.submit': 'إرسال التقييم',
    'reviews.submitting': 'جاري الإرسال...',
    'reviews.loginRequired': 'يجب تسجيل الدخول لكتابة تقييم',
    'reviews.recentReviews': 'تقييمات حديثة',
    'reviews.filterAll': 'جميع المنتجات',
    'reviews.noReviews': 'لا توجد تقييمات بعد. كن أول من يكتب تقييم!',
    'reviews.thankYou': 'شكرًا على تقييمك! 🍪',
    'reviews.reviewAdded': 'تمت إضافة تقييمك بنجاح',
    'reviews.reviewsCount': 'تقييمات',
    
    // FAQ
    'faq.title': 'أسئلة شائعة',
    'faq.subtitle': 'هنا ستجد إجابات على الأسئلة الأكثر شيوعًا. لم تجد ما تبحث عنه؟ تواصل معنا!',
    'faq.delivery': 'كيف يعمل التوصيل؟',
    'faq.deliveryAnswer': 'التوصيل من الأحد إلى الخميس، 10:00-20:00. تكلفة الشحن ₪25 لجميع أنحاء البلاد، شحن مجاني للطلبات فوق ₪150. مدة التوصيل 1-3 أيام عمل.',
    'faq.payment': 'ما هي طرق الدفع المقبولة؟',
    'faq.paymentAnswer': 'حاليًا نقبل الدفع نقدًا عند التوصيل فقط. سيتم إضافة الدفع ببطاقة الائتمان قريبًا.',
    'faq.freshness': 'كم تبقى المنتجات طازجة؟',
    'faq.freshnessAnswer': 'منتجاتنا تُحضر طازجة لكل طلب وتبقى طازجة حتى 5 أيام في درجة حرارة الغرفة أو حتى أسبوعين في الثلاجة. ننصح بتسخينها في الميكروويف 10 ثوانٍ لتجربة مثالية!',
    'faq.allergens': 'ماذا عن مسببات الحساسية؟',
    'faq.allergensAnswer': 'جميع كوكيزنا تحتوي على غلوتين ومنتجات ألبان وبيض. بعض الكوكيز تحتوي على مكسرات أو فول سوداني أو صويا. إذا كان لديك حساسية معينة، يرجى ذكرها في ملاحظات الطلب.',
    'faq.events': 'هل يمكنني الطلب للمناسبات؟',
    'faq.eventsAnswer': 'بالتأكيد! نقدم باقات خاصة للمناسبات وأعياد الميلاد والأعراس. تواصل معنا للحصول على عرض سعر مخصص.',
    'faq.contact': 'كيف يمكنني التواصل معكم؟',
    'faq.contactAnswer': 'يمكنك التواصل معنا عبر واتساب من الزر العائم أدناه، أو عبر النموذج في الموقع، أو بالهاتف 054-6791198. نحن متاحون من الأحد إلى الخميس بين 9:00-21:00.',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.address': 'شارع كاديش 39، أشكلون',
    'contact.phone': '054-679-1198',
    'contact.hours': 'التوصيل خلال 3 أيام عمل',
    
    // Cart
    'cart.title': 'سلتك',
    'cart.empty': 'السلة فارغة',
    'cart.total': 'المجموع',
    'cart.checkout': 'الدفع',
    'cart.remove': 'إزالة',
    'cart.quantity': 'الكمية',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.free': 'مجاني',
    
    // Checkout
    'checkout.title': 'تفاصيل الطلب',
    'checkout.name': 'الاسم الكامل',
    'checkout.phone': 'الهاتف',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.notes': 'ملاحظات الطلب',
    'checkout.submit': 'إرسال الطلب',
    'checkout.success': 'تم إرسال الطلب بنجاح!',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.loginButton': 'تسجيل الدخول',
    'auth.signupButton': 'إنشاء حساب',
    'auth.orContinueWith': 'أو المتابعة مع',
    'auth.phoneLogin': 'الدخول بالهاتف',
    'auth.verifyCode': 'تحقق من الرمز',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.registerTitle': 'إنشاء حساب',
    'auth.forgotTitle': 'نسيت كلمة المرور',
    'auth.or': 'أو',
    'auth.fullNameLabel': 'الاسم الكامل *',
    'auth.emailLabel': 'البريد الإلكتروني *',
    'auth.passwordLabel': 'كلمة المرور *',
    'auth.passwordPlaceholder': '6 أحرف على الأقل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.loggingIn': 'جاري الدخول...',
    'auth.registering': 'جاري التسجيل...',
    'auth.loginBtn': 'تسجيل الدخول',
    'auth.registerBtn': 'إنشاء حساب',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signupLink': 'سجل الآن',
    'auth.loginLink': 'سجل الدخول',
    'auth.error': 'خطأ',
    'auth.genericError': 'حدث خطأ، حاول مرة أخرى',
    
    // Profile
    'profile.title': 'ملفي الشخصي',
    'profile.edit': 'تعديل الملف',
    'profile.save': 'حفظ',
    'profile.cancel': 'إلغاء',
    'profile.deleteAccount': 'حذف الحساب',
    'profile.changePassword': 'تغيير كلمة المرور',
    
    // Newsletter
    'newsletter.title': 'لا تفوت العروض!',
    'newsletter.subtitle': 'اشترك في نشرتنا الإخبارية للحصول على عروض خاصة',
    'newsletter.emailPlaceholder': 'بريدك الإلكتروني',
    'newsletter.phonePlaceholder': 'رقم الهاتف (اختياري)',
    'newsletter.button': 'اشترك الآن ✨',
    'newsletter.submitting': 'جاري الإرسال...',
    'newsletter.success': 'تم الاشتراك بنجاح! 🎉',
    'newsletter.noSpam': 'نعدك بعدم إرسال رسائل مزعجة. فقط أخبار لذيذة. ✨',
    
    // Footer
    'footer.rights': 'جميع الحقوق محفوظة',
    
    // General
    'general.loading': 'جاري التحميل...',
    'general.error': 'خطأ',
    'general.success': 'نجاح',
    'general.close': 'إغلاق',
    'general.back': 'رجوع',
    'general.next': 'التالي',
    'general.confirm': 'تأكيد',
    'general.delete': 'حذف',
    'general.edit': 'تعديل',
    'general.save': 'حفظ',
    'general.cancel': 'إلغاء',
    
    // Gift
    'gift.title': 'باقات الهدايا',
    'gift.subtitle': 'صمم باقة هدايا مثالية مع الكوكيز المفضلة لديك',
    'gift.addToCart': 'أضف للسلة',
    'gift.small': 'باقة صغيرة',
    'gift.medium': 'باقة متوسطة',
    'gift.large': 'باقة كبيرة',
    'gift.total': 'المجموع:',
    'gift.cookies': 'كوكيز',
    
    // Cart Modal
    'cartModal.title': 'سلتي',
    'cartModal.empty': 'السلة فارغة',
    'cartModal.total': 'المجموع:',
    'cartModal.continue': 'متابعة الطلب',
    
    // Cookie Card
    'cookieCard.added': 'تمت الإضافة!',
    'cookieCard.add': 'أضف',
    'cookieCard.addToCart': 'أضف للسلة',
    'cookieCard.recommended': 'موصى به',
    'cookieCard.new': 'جديد',

    // Order History
    'orderHistory.title': 'سجل الطلبات',
    'orderHistory.myOrders': 'طلباتي',
    'orderHistory.noOrders': 'لا توجد طلبات سابقة',
    'orderHistory.pending': 'قيد الانتظار',
    'orderHistory.confirmed': 'مؤكد',
    'orderHistory.preparing': 'قيد التحضير',
    'orderHistory.delivering': 'قيد التوصيل',
    'orderHistory.completed': 'مكتمل',
    'orderHistory.cancelled': 'ملغي',

    // Checkout Form
    'checkoutForm.fullName': 'الاسم الكامل',
    'checkoutForm.phone': 'الهاتف',
    'checkoutForm.city': 'المدينة',
    'checkoutForm.address': 'العنوان',
    'checkoutForm.totalPayment': 'المجموع للدفع:',
    'checkoutForm.cashPayment': '💵 دفع نقدي عند التوصيل',
    'checkoutForm.orderCash': 'طلب بالنقد',
    'checkoutForm.sending': 'جاري الإرسال...',

    // UI Labels
    'ui.infoBanner': 'شريط المعلومات',
    'ui.socialMedia': 'وسائل التواصل الاجتماعي',
    'ui.boutiqueSubtitle': 'كوكيز بوتيك مصنوعة يدويًا · نكهات لا تُنسى',
    'ui.brandName': 'مزون السعادة',
    'ui.greeting.morning': 'صباح الخير',
    'ui.greeting.afternoon': 'طاب نهارك',
    'ui.greeting.evening': 'مساء الخير',
    'ui.greeting.night': 'تصبح على خير',
    'ui.boutiqueShort': 'كوكيز بوتيك مصنوعة يدويًا',
    'ui.loading': 'جاري التحميل...',
    'notFound.connecting': 'جاري الاتصال...',
    'notFound.metaTitle': '404 | الصفحة غير موجودة — مازون هاأوشر',
    'notFound.metaDescription': 'الصفحة التي تبحث عنها غير موجودة. عُد إلى الصفحة الرئيسية لمازون هاأوشر للاستمتاع ببسكويت أمريكي مصنوع يدويًا.',
    'notFound.title': 'عفوًا! تم أكل هذه البسكويتة',
    'notFound.subtitle': 'الصفحة التي تبحث عنها غير موجودة، ولكن لدينا الكثير من البسكويت الطازج في الصفحة الرئيسية',
    'notFound.home': 'العودة إلى الرئيسية',
    'notFound.back': 'العودة للخلف',
    'notFound.requestedPath': 'المسار المطلوب:',
    'ui.skipToContent': 'تخطي إلى المحتوى الرئيسي',
    'ui.displayMode': 'وضع العرض',
    'ui.themeLight': 'فاتح',
    'ui.themeDark': 'داكن',
    'ui.themeAuto': 'تلقائي',
    'ui.a11yMenu': 'قائمة إمكانية الوصول',
    'ui.a11yClose': 'إغلاق قائمة إمكانية الوصول',
    'ui.a11yContent': 'المحتوى',
    'ui.a11yFontSize': 'حجم الخط',
    'ui.a11yLineHeight': 'ارتفاع السطر',
    'ui.a11yTextAlign': 'محاذاة النص',
    'ui.a11yDisplay': 'العرض',
    'ui.a11yNavigation': 'التنقل والقراءة',
    'ui.a11yHighContrast': 'تباين عالي',
    'ui.a11yInvertColors': 'عكس الألوان',
    'ui.a11yHighlightLinks': 'تمييز الروابط',
    'ui.a11yHighlightTitles': 'تمييز العناوين',
    'ui.a11yHideImages': 'إخفاء الصور',
    'ui.a11yBigCursor': 'مؤشر كبير',
    'ui.a11yReadingGuide': 'دليل القراءة',
    'ui.a11yReduceMotion': 'تقليل الحركة',
    'ui.a11yReadableFont': 'خط مقروء',
    'ui.a11yTextSpacing': 'تباعد النص',
    'ui.a11yHighlightFocus': 'تمييز التركيز',
    'ui.a11yReset': 'إعادة تعيين جميع الإعدادات',
    'ui.a11yFontNormal': 'عادي',
    'ui.a11yFontLarge': 'كبير',
    'ui.a11yFontLarger': 'أكبر',
    'ui.a11yFontHuge': 'ضخم',
    'ui.a11yLineNormal': 'عادي',
    'ui.a11yLineLarge': 'كبير',
    'ui.a11yLineXL': 'XL',
    'ui.a11ySatNormal': 'عادي',
    'ui.a11ySatLow': 'تشبع منخفض',
    'ui.a11ySatGray': 'رمادي',
    'ui.a11yAlignDefault': 'افتراضي',
    'ui.a11yAlignRight': 'يمين',
    'ui.a11yAlignCenter': 'وسط',
    'ui.a11yAlignLeft': 'يسار',
  },
  ru: {
    // Header
    'nav.home': 'Главная',
    'nav.cookies': 'Печенье',
    'nav.about': 'О нас',
    'nav.reviews': 'Отзывы',
    'nav.faq': 'Вопросы',
    'nav.contact': 'Контакты',
    'nav.cart': 'Корзина',
    'nav.profile': 'Профиль',
    'nav.login': 'Вход',
    'nav.logout': 'Выход',
    'nav.orderHistory': 'История заказов',
    'nav.editProfile': 'Редактировать профиль',
    
    // Hero
    'hero.title': 'Мазон ХаОшер',
    'hero.subtitle': 'Гигантское американское печенье',
    'hero.description': 'Гигантское американское печенье ручной работы из лучших ингредиентов',
    'hero.cta': 'Смотреть меню',
    'hero.madeWithLove': 'Сделано с любовью',
    'hero.viewMenu': 'Смотреть меню',
    
    // Cookies Section
    'cookies.title': 'Наша коллекция',
    'cookies.subtitle': 'Сделано с любовью, специально для вас ✨',
    'cookies.addToCart': 'В корзину',
    'cookies.outOfStock': 'Нет в наличии',
    'cookies.price': '₪',
    'cookies.search': 'Поиск...',
    'cookies.all': 'Все',
    'cookies.chocolate': 'Шоколад',
    'cookies.fruits': 'Фрукты',
    'cookies.candy': 'Конфеты',
    'cookies.nuts': 'Орехи',
    'cookies.classic': 'Классика',
    'cookies.recommended': 'Рекомендуем',
    'cookies.new': 'Новинка',
    'cookies.favorites': 'Избранное',
    'cookies.sortDefault': 'По умолчанию',
    'cookies.sortName': 'По имени',
    'cookies.sortPrice': 'По цене',
    'cookies.noResults': 'Печенье не найдено',
    'cookies.clearFilters': 'Сбросить фильтры',
    
    // Cookie names
    'cookie.lotus': 'Лотус',
    'cookie.kinder': 'Киндер',
    'cookie.kinderBueno': 'Киндер Буэно',
    'cookie.redVelvet': 'Ред Вельвет',
    'cookie.confetti': 'Конфетти',
    'cookie.pistachio': 'Фисташка',
    'cookie.pretzel': 'Крендель',
    'cookie.chocolateChip': 'Шоколадная крошка',
    'cookie.oreo': 'Орео',
    'cookie.peanutButter': 'Арахисовая паста',
    'cookie.lemon': 'Лимон',
    'cookie.macadamia': 'Макадамия',
    'cookie.oatmeal': 'Овсяное',
    'cookie.saltedCaramel': 'Солёная карамель',
    'cookie.tahini': 'Тахини',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'Печенье Лотус и карамельная паста',
    'cookie.kinderDesc': 'Шоколад Киндер с цветными шоколадными шариками',
    'cookie.kinderBuenoDesc': 'Киндер Буэно, молочный шоколад и шоколадная глазурь',
    'cookie.redVelvetDesc': 'Тесто Ред Вельвет, белый шоколад и малиновая крошка',
    'cookie.confettiDesc': 'Цветная посыпка и Смартис',
    'cookie.pistachioDesc': 'Белый шоколад, жареные фисташки и зёрна граната',
    'cookie.pretzelDesc': 'Солёный крендель, белый шоколад и шоколадная крошка',
    'cookie.chocolateChipDesc': 'Бельгийский тёмный и молочный шоколад',
    'cookie.oreoDesc': 'Крошка Орео, белый шоколад и ванильный крем',
    'cookie.peanutButterDesc': 'Арахисовая паста, жареный арахис и шоколад',
    'cookie.lemonDesc': 'Свежая цедра лимона с сахарной глазурью',
    'cookie.macadamiaDesc': 'Орехи макадамия и белый шоколад',
    'cookie.oatmealDesc': 'Овсянка, изюм и корица',
    'cookie.saltedCaramelDesc': 'Домашняя карамель с кристаллами морской соли',
    'cookie.tahiniDesc': 'Тахини, кунжут и мёд',
    
    // Cookie of the Week
    'cotw.title': 'Печенье недели',
    'cotw.discount': 'Скидка',
    'cotw.originalPrice': 'Обычная цена',
    'cotw.salePrice': 'Цена со скидкой',
    'cotw.badge': 'Печенье недели',
    'cotw.add': 'Добавить',
    
    // About
    'about.title': 'О Мазон ХаОшер',
    'about.ourStory': 'Наша история',
    'about.headline': 'Создаём счастье, одно творение за раз',
    'about.description': 'Мазон ХаОшер начался на маленькой домашней кухне с простой мечтой: поделиться теплом и уютом домашней выпечки с нашим сообществом.',
    'about.madeWithLove': 'Сделано с любовью',
    'about.madeWithLoveDesc': 'Каждая партия готовится с заботой и страстью, как у бабушки.',
    'about.freshIngredients': 'Свежие ингредиенты',
    'about.freshIngredientsDesc': 'Мы используем только самые свежие и лучшие ингредиенты.',
    'about.dailyPrep': 'Ежедневное приготовление',
    'about.dailyPrepDesc': 'Наша продукция готовится свежей каждое утро для идеального вкуса.',
    
    // Reviews
    'reviews.title': 'Что говорят наши клиенты',
    'reviews.subtitle': 'Отзывы довольных клиентов',
    'reviews.addReview': 'Добавить отзыв',
    'reviews.selectProduct': 'Выберите продукт',
    'reviews.selectProductPlaceholder': 'Выберите продукт...',
    'reviews.rating': 'Рейтинг',
    'reviews.yourReview': 'Ваш отзыв (необязательно, до 500 символов)',
    'reviews.reviewPlaceholder': 'Расскажите нам своё мнение...',
    'reviews.submit': 'Отправить отзыв',
    'reviews.submitting': 'Отправка...',
    'reviews.loginRequired': 'Для написания отзыва необходимо войти',
    'reviews.recentReviews': 'Последние отзывы',
    'reviews.filterAll': 'Все продукты',
    'reviews.noReviews': 'Пока нет отзывов. Будьте первым!',
    'reviews.thankYou': 'Спасибо за отзыв! 🍪',
    'reviews.reviewAdded': 'Ваш отзыв успешно добавлен',
    'reviews.reviewsCount': 'отзывов',
    
    // FAQ
    'faq.title': 'Часто задаваемые вопросы',
    'faq.subtitle': 'Здесь вы найдёте ответы на самые частые вопросы. Не нашли ответ? Свяжитесь с нами!',
    'faq.delivery': 'Как работает доставка?',
    'faq.deliveryAnswer': 'Доставка с воскресенья по четверг, 10:00-20:00. Стоимость доставки ₪25 по всей стране, бесплатная доставка при заказе от ₪150. Срок доставки 1-3 рабочих дня.',
    'faq.payment': 'Какие способы оплаты принимаются?',
    'faq.paymentAnswer': 'В настоящее время мы принимаем только наличные при доставке. Оплата картой будет добавлена в ближайшее время.',
    'faq.freshness': 'Как долго продукты остаются свежими?',
    'faq.freshnessAnswer': 'Наши продукты готовятся свежими для каждого заказа и остаются свежими до 5 дней при комнатной температуре или до двух недель в холодильнике. Рекомендуем разогреть в микроволновке 10 секунд!',
    'faq.allergens': 'Как насчёт аллергенов?',
    'faq.allergensAnswer': 'Все наши печенья содержат глютен, молочные продукты и яйца. Некоторые содержат орехи, арахис или сою. Если у вас есть аллергия, укажите это в примечаниях к заказу.',
    'faq.events': 'Можно заказать для мероприятий?',
    'faq.eventsAnswer': 'Конечно! Мы предлагаем специальные наборы для мероприятий, дней рождения и свадеб. Свяжитесь с нами для индивидуального предложения.',
    'faq.contact': 'Как с вами связаться?',
    'faq.contactAnswer': 'Вы можете связаться с нами через WhatsApp, форму на сайте или по телефону 054-6791198. Мы доступны с воскресенья по четверг с 9:00 до 21:00.',
    
    // Contact
    'contact.title': 'Контакты',
    'contact.address': 'бульвар Кадеш 39, Ашкелон',
    'contact.phone': '054-679-1198',
    'contact.hours': 'Доставка в течение 3 рабочих дней',
    
    // Cart
    'cart.title': 'Ваша корзина',
    'cart.empty': 'Корзина пуста',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить',
    'cart.remove': 'Удалить',
    'cart.quantity': 'Количество',
    'cart.subtotal': 'Подытог',
    'cart.shipping': 'Доставка',
    'cart.free': 'Бесплатно',
    
    // Checkout
    'checkout.title': 'Детали заказа',
    'checkout.name': 'Полное имя',
    'checkout.phone': 'Телефон',
    'checkout.address': 'Адрес',
    'checkout.city': 'Город',
    'checkout.notes': 'Примечания к заказу',
    'checkout.submit': 'Отправить заказ',
    'checkout.success': 'Заказ успешно отправлен!',
    
    // Auth
    'auth.login': 'Вход',
    'auth.signup': 'Регистрация',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',
    'auth.loginButton': 'Войти',
    'auth.signupButton': 'Зарегистрироваться',
    'auth.orContinueWith': 'Или продолжить с',
    'auth.loginTitle': 'Вход',
    'auth.registerTitle': 'Регистрация',
    'auth.forgotTitle': 'Забыли пароль',
    'auth.or': 'или',
    'auth.fullNameLabel': 'Полное имя *',
    'auth.emailLabel': 'Эл. почта *',
    'auth.passwordLabel': 'Пароль *',
    'auth.passwordPlaceholder': 'Минимум 6 символов',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.loggingIn': 'Вход...',
    'auth.registering': 'Регистрация...',
    'auth.loginBtn': 'Войти',
    'auth.registerBtn': 'Зарегистрироваться',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.signupLink': 'Зарегистрироваться',
    'auth.loginLink': 'Войти',
    'auth.error': 'Ошибка',
    'auth.genericError': 'Произошла ошибка, попробуйте снова',
    
    // Profile
    'profile.title': 'Мой профиль',
    'profile.edit': 'Редактировать',
    'profile.save': 'Сохранить',
    'profile.cancel': 'Отмена',
    'profile.deleteAccount': 'Удалить аккаунт',
    'profile.changePassword': 'Сменить пароль',
    
    // Newsletter
    'newsletter.title': 'Не пропустите акции!',
    'newsletter.subtitle': 'Подпишитесь на рассылку для специальных предложений',
    'newsletter.emailPlaceholder': 'Ваш email',
    'newsletter.phonePlaceholder': 'Телефон (необязательно)',
    'newsletter.button': 'Подписаться ✨',
    'newsletter.submitting': 'Отправка...',
    'newsletter.success': 'Подписка оформлена! 🎉',
    'newsletter.noSpam': 'Мы обещаем не отправлять спам. Только вкусные новости. ✨',
    
    // Footer
    'footer.rights': 'Все права защищены',
    
    // General
    'general.loading': 'Загрузка...',
    'general.error': 'Ошибка',
    'general.success': 'Успех',
    'general.close': 'Закрыть',
    'general.back': 'Назад',
    'general.next': 'Далее',
    'general.confirm': 'Подтвердить',
    'general.delete': 'Удалить',
    'general.edit': 'Редактировать',
    'general.save': 'Сохранить',
    'general.cancel': 'Отмена',
    
    // Gift
    'gift.title': 'Подарочные наборы',
    'gift.subtitle': 'Создайте идеальный подарочный набор с любимым печеньем',
    'gift.addToCart': 'В корзину',
    'gift.small': 'Маленький набор',
    'gift.medium': 'Средний набор',
    'gift.large': 'Большой набор',
    'gift.total': 'Итого:',
    'gift.cookies': 'печенья',
    
    // Cart Modal
    'cartModal.title': 'Моя корзина',
    'cartModal.empty': 'Корзина пуста',
    'cartModal.total': 'Итого:',
    'cartModal.continue': 'Продолжить заказ',
    
    // Cookie Card
    'cookieCard.added': 'Добавлено!',
    'cookieCard.add': 'Добавить',
    'cookieCard.addToCart': 'В корзину',
    'cookieCard.recommended': 'Рекомендуем',
    'cookieCard.new': 'Новинка',

    // Order History
    'orderHistory.title': 'История заказов',
    'orderHistory.myOrders': 'Мои заказы',
    'orderHistory.noOrders': 'Нет предыдущих заказов',
    'orderHistory.pending': 'В ожидании',
    'orderHistory.confirmed': 'Подтверждён',
    'orderHistory.preparing': 'Готовится',
    'orderHistory.delivering': 'Доставляется',
    'orderHistory.completed': 'Завершён',
    'orderHistory.cancelled': 'Отменён',

    // Checkout Form
    'checkoutForm.fullName': 'Полное имя',
    'checkoutForm.phone': 'Телефон',
    'checkoutForm.city': 'Город',
    'checkoutForm.address': 'Адрес',
    'checkoutForm.totalPayment': 'Итого к оплате:',
    'checkoutForm.cashPayment': '💵 Оплата наличными при доставке',
    'checkoutForm.orderCash': 'Заказать за наличные',
    'checkoutForm.sending': 'Отправка...',

    // UI Labels
    'ui.infoBanner': 'Информационный баннер',
    'ui.socialMedia': 'Социальные сети',
    'ui.boutiqueSubtitle': 'Бутиковое печенье ручной работы · Незабываемые вкусы',
    'ui.brandName': 'Мазон ХаОшер',
    'ui.greeting.morning': 'Доброе утро',
    'ui.greeting.afternoon': 'Добрый день',
    'ui.greeting.evening': 'Добрый вечер',
    'ui.greeting.night': 'Доброй ночи',
    'ui.boutiqueShort': 'Бутиковое печенье ручной работы',
    'ui.loading': 'Загрузка...',
    'notFound.connecting': 'Подключение...',
    'notFound.metaTitle': '404 | Страница не найдена — Mazon HaOsher',
    'notFound.metaDescription': 'Страница, которую вы ищете, не существует. Вернитесь на главную страницу Mazon HaOsher и насладитесь американским печеньем ручной работы.',
    'notFound.title': 'Упс! Это печенье уже съели',
    'notFound.subtitle': 'Страница, которую вы ищете, не существует, но у нас много свежего печенья на главной странице',
    'notFound.home': 'На главную',
    'notFound.back': 'Назад',
    'notFound.requestedPath': 'Запрошенный путь:',
    'ui.skipToContent': 'Перейти к основному содержанию',
    'ui.displayMode': 'Режим отображения',
    'ui.themeLight': 'Светлая',
    'ui.themeDark': 'Тёмная',
    'ui.themeAuto': 'Авто',
    'ui.a11yMenu': 'Меню доступности',
    'ui.a11yClose': 'Закрыть меню доступности',
    'ui.a11yContent': 'Контент',
    'ui.a11yFontSize': 'Размер шрифта',
    'ui.a11yLineHeight': 'Высота строки',
    'ui.a11yTextAlign': 'Выравнивание',
    'ui.a11yDisplay': 'Отображение',
    'ui.a11yNavigation': 'Навигация и чтение',
    'ui.a11yHighContrast': 'Высокий контраст',
    'ui.a11yInvertColors': 'Инвертировать',
    'ui.a11yHighlightLinks': 'Выделить ссылки',
    'ui.a11yHighlightTitles': 'Выделить заголовки',
    'ui.a11yHideImages': 'Скрыть изображения',
    'ui.a11yBigCursor': 'Большой курсор',
    'ui.a11yReadingGuide': 'Линейка чтения',
    'ui.a11yReduceMotion': 'Без анимации',
    'ui.a11yReadableFont': 'Читаемый шрифт',
    'ui.a11yTextSpacing': 'Межбуквенный',
    'ui.a11yHighlightFocus': 'Выделить фокус',
    'ui.a11yReset': 'Сбросить все настройки',
    'ui.a11yFontNormal': 'Обычный',
    'ui.a11yFontLarge': 'Большой',
    'ui.a11yFontLarger': 'Больше',
    'ui.a11yFontHuge': 'Огромный',
    'ui.a11yLineNormal': 'Обычная',
    'ui.a11yLineLarge': 'Большая',
    'ui.a11yLineXL': 'XL',
    'ui.a11ySatNormal': 'Обычная',
    'ui.a11ySatLow': 'Низкая',
    'ui.a11ySatGray': 'Ч/Б',
    'ui.a11yAlignDefault': 'По умолч.',
    'ui.a11yAlignRight': 'Право',
    'ui.a11yAlignCenter': 'Центр',
    'ui.a11yAlignLeft': 'Лево',
  },
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.cookies': 'Galletas',
    'nav.about': 'Nosotros',
    'nav.reviews': 'Reseñas',
    'nav.faq': 'Preguntas frecuentes',
    'nav.contact': 'Contacto',
    'nav.cart': 'Carrito',
    'nav.profile': 'Perfil',
    'nav.login': 'Iniciar sesión',
    'nav.logout': 'Cerrar sesión',
    'nav.orderHistory': 'Historial de pedidos',
    'nav.editProfile': 'Editar perfil',
    
    // Hero
    'hero.title': 'Mazon HaOsher',
    'hero.subtitle': 'Galletas americanas gigantes',
    'hero.description': 'Galletas americanas gigantes hechas a mano con los mejores ingredientes',
    'hero.cta': 'Ver nuestras galletas',
    'hero.madeWithLove': 'Hecho con amor',
    'hero.viewMenu': 'Ver menú',
    
    // Cookies Section
    'cookies.title': 'Nuestra colección',
    'cookies.subtitle': 'Hecho con amor, especialmente para ti ✨',
    'cookies.addToCart': 'Agregar al carrito',
    'cookies.outOfStock': 'Agotado',
    'cookies.price': '₪',
    'cookies.search': 'Buscar...',
    'cookies.all': 'Todo',
    'cookies.chocolate': 'Chocolate',
    'cookies.fruits': 'Frutas',
    'cookies.candy': 'Dulces',
    'cookies.nuts': 'Nueces',
    'cookies.classic': 'Clásico',
    'cookies.recommended': 'Recomendado',
    'cookies.new': 'Nuevo',
    'cookies.favorites': 'Favoritos',
    'cookies.sortDefault': 'Predeterminado',
    'cookies.sortName': 'Por nombre',
    'cookies.sortPrice': 'Por precio',
    'cookies.noResults': 'No se encontraron galletas',
    'cookies.clearFilters': 'Limpiar filtros',
    
    // Cookie names
    'cookie.lotus': 'Lotus',
    'cookie.kinder': 'Kinder',
    'cookie.kinderBueno': 'Kinder Bueno',
    'cookie.redVelvet': 'Red Velvet',
    'cookie.confetti': 'Confeti',
    'cookie.pistachio': 'Pistacho',
    'cookie.pretzel': 'Pretzel',
    'cookie.chocolateChip': 'Chispas de chocolate',
    'cookie.oreo': 'Oreo',
    'cookie.peanutButter': 'Mantequilla de maní',
    'cookie.lemon': 'Limón',
    'cookie.macadamia': 'Macadamia',
    'cookie.oatmeal': 'Avena',
    'cookie.saltedCaramel': 'Caramelo salado',
    'cookie.tahini': 'Tahini',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'Galleta Lotus y crema de caramelo',
    'cookie.kinderDesc': 'Chocolate Kinder con bolitas de chocolate de colores',
    'cookie.kinderBuenoDesc': 'Kinder Bueno, chocolate con leche y cobertura de chocolate',
    'cookie.redVelvetDesc': 'Masa red velvet, chocolate blanco y migas de frambuesa',
    'cookie.confettiDesc': 'Chispas de colores y Smarties',
    'cookie.pistachioDesc': 'Chocolate blanco, pistachos tostados y semillas de granada',
    'cookie.pretzelDesc': 'Pretzel salado, chocolate blanco y chispas de chocolate',
    'cookie.chocolateChipDesc': 'Chispas de chocolate belga oscuro y con leche',
    'cookie.oreoDesc': 'Migas de Oreo, chocolate blanco y crema de vainilla',
    'cookie.peanutButterDesc': 'Mantequilla de maní, maní tostado y chocolate',
    'cookie.lemonDesc': 'Ralladura de limón fresco con glaseado de azúcar',
    'cookie.macadamiaDesc': 'Nueces de macadamia y chocolate blanco',
    'cookie.oatmealDesc': 'Avena, pasas y canela',
    'cookie.saltedCaramelDesc': 'Caramelo casero con cristales de sal marina',
    'cookie.tahiniDesc': 'Tahini crudo, sésamo y miel',
    
    // Cookie of the Week
    'cotw.title': 'Galleta de la semana',
    'cotw.discount': 'Descuento',
    'cotw.originalPrice': 'Precio original',
    'cotw.salePrice': 'Precio de oferta',
    'cotw.badge': 'Galleta de la semana',
    'cotw.add': 'Agregar',
    
    // About
    'about.title': 'Sobre Mazon HaOsher',
    'about.ourStory': 'Nuestra historia',
    'about.headline': 'Creando felicidad, una creación a la vez',
    'about.description': 'Mazon HaOsher comenzó en una pequeña cocina casera con un sueño simple: compartir el calor y la comodidad de los productos horneados caseros con nuestra comunidad.',
    'about.madeWithLove': 'Hecho con amor',
    'about.madeWithLoveDesc': 'Cada lote se prepara con cuidado y pasión, como lo hacía la abuela.',
    'about.freshIngredients': 'Ingredientes frescos',
    'about.freshIngredientsDesc': 'Usamos solo los ingredientes más frescos y finos.',
    'about.dailyPrep': 'Preparación diaria',
    'about.dailyPrepDesc': 'Nuestros productos se preparan frescos cada mañana para un sabor perfecto.',
    
    // Reviews
    'reviews.title': 'Lo que dicen nuestros clientes',
    'reviews.subtitle': 'Reseñas de clientes satisfechos',
    'reviews.addReview': 'Agregar reseña',
    'reviews.selectProduct': 'Seleccionar producto',
    'reviews.selectProductPlaceholder': 'Seleccionar producto...',
    'reviews.rating': 'Calificación',
    'reviews.yourReview': 'Tu reseña (opcional, hasta 500 caracteres)',
    'reviews.reviewPlaceholder': 'Cuéntanos qué pensaste...',
    'reviews.submit': 'Enviar reseña',
    'reviews.submitting': 'Enviando...',
    'reviews.loginRequired': 'Debes iniciar sesión para escribir una reseña',
    'reviews.recentReviews': 'Reseñas recientes',
    'reviews.filterAll': 'Todos los productos',
    'reviews.noReviews': 'Aún no hay reseñas. ¡Sé el primero en escribir una!',
    'reviews.thankYou': '¡Gracias por tu reseña! 🍪',
    'reviews.reviewAdded': 'Tu reseña se ha agregado exitosamente',
    'reviews.reviewsCount': 'reseñas',
    
    // FAQ
    'faq.title': 'Preguntas frecuentes',
    'faq.subtitle': 'Aquí encontrarás respuestas a las preguntas más comunes. ¿No encontraste lo que buscabas? ¡Contáctanos!',
    'faq.delivery': '¿Cómo funciona la entrega?',
    'faq.deliveryAnswer': 'Las entregas se realizan de domingo a jueves, 10:00-20:00. El envío cuesta ₪25 a todo el país, envío gratis en pedidos superiores a ₪150. Tiempo de entrega: 1-3 días hábiles.',
    'faq.payment': '¿Qué métodos de pago aceptan?',
    'faq.paymentAnswer': 'Actualmente aceptamos pago en efectivo al momento de la entrega. Pronto agregaremos pago con tarjeta de crédito.',
    'faq.freshness': '¿Cuánto tiempo se mantienen frescos los productos?',
    'faq.freshnessAnswer': 'Nuestros productos se preparan frescos para cada pedido y se mantienen frescos hasta 5 días a temperatura ambiente o hasta dos semanas en el refrigerador. ¡Recomendamos calentar en el microondas 10 segundos!',
    'faq.allergens': '¿Qué hay sobre los alérgenos?',
    'faq.allergensAnswer': 'Todas nuestras galletas contienen gluten, lácteos y huevos. Algunas contienen nueces, maní o soja. Si tienes una alergia específica, indícalo en las notas del pedido.',
    'faq.events': '¿Puedo pedir para eventos?',
    'faq.eventsAnswer': '¡Por supuesto! Ofrecemos paquetes especiales para eventos, cumpleaños y bodas. Contáctanos para una cotización personalizada.',
    'faq.contact': '¿Cómo puedo contactarlos?',
    'faq.contactAnswer': 'Puedes contactarnos por WhatsApp con el botón flotante, a través del formulario web o por teléfono al 054-6791198. Estamos disponibles de domingo a jueves de 9:00 a 21:00.',
    
    // Contact
    'contact.title': 'Contacto',
    'contact.address': 'Blvd. Kadesh 39, Ashkelon',
    'contact.phone': '054-679-1198',
    'contact.hours': 'Entrega en 3 días hábiles',
    
    // Cart
    'cart.title': 'Tu carrito',
    'cart.empty': 'El carrito está vacío',
    'cart.total': 'Total',
    'cart.checkout': 'Pagar',
    'cart.remove': 'Eliminar',
    'cart.quantity': 'Cantidad',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.free': 'Gratis',
    
    // Checkout
    'checkout.title': 'Detalles del pedido',
    'checkout.name': 'Nombre completo',
    'checkout.phone': 'Teléfono',
    'checkout.address': 'Dirección',
    'checkout.city': 'Ciudad',
    'checkout.notes': 'Notas del pedido',
    'checkout.submit': 'Realizar pedido',
    'checkout.success': '¡Pedido realizado con éxito!',
    
    // Auth
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.loginButton': 'Iniciar sesión',
    'auth.signupButton': 'Registrarse',
    'auth.orContinueWith': 'O continuar con',
    'auth.loginTitle': 'Iniciar sesión',
    'auth.registerTitle': 'Registrarse',
    'auth.forgotTitle': 'Olvidé mi contraseña',
    'auth.or': 'o',
    'auth.fullNameLabel': 'Nombre completo *',
    'auth.emailLabel': 'Correo electrónico *',
    'auth.passwordLabel': 'Contraseña *',
    'auth.passwordPlaceholder': 'Mínimo 6 caracteres',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.loggingIn': 'Iniciando sesión...',
    'auth.registering': 'Registrando...',
    'auth.loginBtn': 'Iniciar sesión',
    'auth.registerBtn': 'Registrarse',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.signupLink': 'Regístrate',
    'auth.loginLink': 'Inicia sesión',
    'auth.error': 'Error',
    'auth.genericError': 'Ocurrió un error, intenta de nuevo',
    
    // Profile
    'profile.title': 'Mi perfil',
    'profile.edit': 'Editar perfil',
    'profile.save': 'Guardar',
    'profile.cancel': 'Cancelar',
    'profile.deleteAccount': 'Eliminar cuenta',
    'profile.changePassword': 'Cambiar contraseña',
    
    // Newsletter
    'newsletter.title': '¡No te pierdas las ofertas!',
    'newsletter.subtitle': 'Suscríbete a nuestro boletín para ofertas especiales',
    'newsletter.emailPlaceholder': 'Tu correo electrónico',
    'newsletter.phonePlaceholder': 'Teléfono (opcional)',
    'newsletter.button': 'Suscribirse ✨',
    'newsletter.submitting': 'Enviando...',
    'newsletter.success': '¡Suscripción exitosa! 🎉',
    'newsletter.noSpam': 'Prometemos no enviar spam. Solo noticias deliciosas. ✨',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados',
    
    // General
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.close': 'Cerrar',
    'general.back': 'Volver',
    'general.next': 'Siguiente',
    'general.confirm': 'Confirmar',
    'general.delete': 'Eliminar',
    'general.edit': 'Editar',
    'general.save': 'Guardar',
    'general.cancel': 'Cancelar',
    
    // Gift
    'gift.title': 'Paquetes de regalo',
    'gift.subtitle': 'Crea el paquete de regalo perfecto con tus galletas favoritas',
    'gift.addToCart': 'Agregar al carrito',
    'gift.small': 'Paquete pequeño',
    'gift.medium': 'Paquete mediano',
    'gift.large': 'Paquete grande',
    'gift.total': 'Total:',
    'gift.cookies': 'galletas',
    
    // Cart Modal
    'cartModal.title': 'Mi carrito',
    'cartModal.empty': 'El carrito está vacío',
    'cartModal.total': 'Total:',
    'cartModal.continue': 'Continuar con el pedido',
    
    // Cookie Card
    'cookieCard.added': '¡Agregado!',
    'cookieCard.add': 'Agregar',
    'cookieCard.addToCart': 'Agregar al carrito',
    'cookieCard.recommended': 'Recomendado',
    'cookieCard.new': 'Nuevo',

    // Order History
    'orderHistory.title': 'Historial de pedidos',
    'orderHistory.myOrders': 'Mis pedidos',
    'orderHistory.noOrders': 'No hay pedidos anteriores',
    'orderHistory.pending': 'Pendiente',
    'orderHistory.confirmed': 'Confirmado',
    'orderHistory.preparing': 'En preparación',
    'orderHistory.delivering': 'En camino',
    'orderHistory.completed': 'Completado',
    'orderHistory.cancelled': 'Cancelado',

    // Checkout Form
    'checkoutForm.fullName': 'Nombre completo',
    'checkoutForm.phone': 'Teléfono',
    'checkoutForm.city': 'Ciudad',
    'checkoutForm.address': 'Dirección',
    'checkoutForm.totalPayment': 'Total a pagar:',
    'checkoutForm.cashPayment': '💵 Pago en efectivo al momento de la entrega',
    'checkoutForm.orderCash': 'Pedir en efectivo',
    'checkoutForm.sending': 'Enviando...',

    // UI Labels
    'ui.infoBanner': 'Banner informativo',
    'ui.socialMedia': 'Redes sociales',
    'ui.boutiqueSubtitle': 'Galletas boutique artesanales · Sabores inolvidables',
    'ui.brandName': 'Mazon HaOsher',
    'ui.greeting.morning': 'Buenos días',
    'ui.greeting.afternoon': 'Buenas tardes',
    'ui.greeting.evening': 'Buenas noches',
    'ui.greeting.night': 'Buenas noches',
    'ui.boutiqueShort': 'Galletas Boutique Artesanales',
    'ui.loading': 'Cargando...',
    'notFound.connecting': 'Conectando...',
    'notFound.metaTitle': '404 | Página no encontrada — Mazon HaOsher',
    'notFound.metaDescription': 'La página que buscas no existe. Vuelve a la página principal de Mazon HaOsher para disfrutar de galletas americanas hechas a mano.',
    'notFound.title': '¡Ups! Esta galleta ya se la comieron',
    'notFound.subtitle': 'La página que buscas no existe, pero tenemos muchas galletas frescas en la página principal',
    'notFound.home': 'Volver al inicio',
    'notFound.back': 'Volver atrás',
    'notFound.requestedPath': 'Ruta solicitada:',
    'ui.skipToContent': 'Saltar al contenido principal',
    'ui.displayMode': 'Modo de pantalla',
    'ui.themeLight': 'Claro',
    'ui.themeDark': 'Oscuro',
    'ui.themeAuto': 'Auto',
    'ui.a11yMenu': 'Menú de accesibilidad',
    'ui.a11yClose': 'Cerrar menú de accesibilidad',
    'ui.a11yContent': 'Contenido',
    'ui.a11yFontSize': 'Tamaño de fuente',
    'ui.a11yLineHeight': 'Altura de línea',
    'ui.a11yTextAlign': 'Alinear texto',
    'ui.a11yDisplay': 'Pantalla',
    'ui.a11yNavigation': 'Navegación y lectura',
    'ui.a11yHighContrast': 'Alto contraste',
    'ui.a11yInvertColors': 'Invertir colores',
    'ui.a11yHighlightLinks': 'Resaltar enlaces',
    'ui.a11yHighlightTitles': 'Resaltar títulos',
    'ui.a11yHideImages': 'Ocultar imágenes',
    'ui.a11yBigCursor': 'Cursor grande',
    'ui.a11yReadingGuide': 'Guía de lectura',
    'ui.a11yReduceMotion': 'Sin animaciones',
    'ui.a11yReadableFont': 'Fuente legible',
    'ui.a11yTextSpacing': 'Espaciado',
    'ui.a11yHighlightFocus': 'Resaltar foco',
    'ui.a11yReset': 'Restablecer todo',
    'ui.a11yFontNormal': 'Normal',
    'ui.a11yFontLarge': 'Grande',
    'ui.a11yFontLarger': 'Más grande',
    'ui.a11yFontHuge': 'Enorme',
    'ui.a11yLineNormal': 'Normal',
    'ui.a11yLineLarge': 'Grande',
    'ui.a11yLineXL': 'XL',
    'ui.a11ySatNormal': 'Normal',
    'ui.a11ySatLow': 'Baja sat.',
    'ui.a11ySatGray': 'Escala gris',
    'ui.a11yAlignDefault': 'Predet.',
    'ui.a11yAlignRight': 'Derecha',
    'ui.a11yAlignCenter': 'Centro',
    'ui.a11yAlignLeft': 'Izquierda',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'he';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    // Update document direction and lang
    const rtlLanguages: Language[] = ['he', 'ar'];
    document.documentElement.dir = rtlLanguages.includes(language) ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = language === 'he' || language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
