import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'he' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  he: {
    // Header
    'nav.home': 'בית',
    'nav.cookies': 'עוגיות',
    'nav.about': 'אודות',
    'nav.reviews': 'ביקורות',
    'nav.faq': 'שאלות נפוצות',
    'nav.contact': 'צור קשר',
    'nav.cart': 'עגלה',
    'nav.profile': 'פרופיל',
    'nav.login': 'התחברות',
    'nav.logout': 'התנתקות',
    'nav.orderHistory': 'היסטוריית הזמנות',
    'nav.editProfile': 'עריכת פרופיל',
    
    // Hero
    'hero.title': 'מזון האושר',
    'hero.subtitle': 'עוגיות אמריקאיות ענקיות',
    'hero.description': 'עוגיות אמריקאיות ענקיות בעבודת יד, עשויות מחומרי הגלם הטובים ביותר',
    'hero.cta': 'לתפריט העוגיות',
    'hero.madeWithLove': 'מיוצר באהבה',
    'hero.viewMenu': 'צפו בתפריט',
    
    // Cookies Section
    'cookies.title': 'הקולקציה שלנו',
    'cookies.subtitle': 'מיוצר באהבה, במיוחד בשבילכם ✨',
    'cookies.addToCart': 'הוסף לעגלה',
    'cookies.outOfStock': 'אזל מהמלאי',
    'cookies.price': '₪',
    'cookies.search': 'חיפוש...',
    'cookies.all': 'הכל',
    'cookies.chocolate': 'שוקולד',
    'cookies.fruits': 'פירות',
    'cookies.candy': 'ממתקים',
    'cookies.nuts': 'אגוזים',
    'cookies.classic': 'קלאסי',
    'cookies.recommended': 'מומלץ',
    'cookies.new': 'חדש',
    'cookies.favorites': 'מועדפים',
    'cookies.sortDefault': 'ברירת מחדל',
    'cookies.sortName': 'לפי שם',
    'cookies.sortPrice': 'לפי מחיר',
    'cookies.noResults': 'לא נמצאו עוגיות',
    'cookies.clearFilters': 'נקה מסננים',
    
    // Cookie names
    'cookie.lotus': 'לוטוס',
    'cookie.kinder': 'קינדר',
    'cookie.kinderBueno': 'קינדר בואנו',
    'cookie.redVelvet': 'רד וולווט',
    'cookie.confetti': 'קונפטי',
    'cookie.pistachio': 'פיסטוק',
    'cookie.pretzel': 'בייגלה',
    'cookie.chocolateChip': 'שוקולד צ׳יפס',
    'cookie.oreo': 'אוראו',
    'cookie.peanutButter': 'חמאת בוטנים',
    'cookie.lemon': 'לימון',
    'cookie.macadamia': 'מקדמיה',
    'cookie.oatmeal': 'שיבולת שועל',
    'cookie.saltedCaramel': 'קרמל מלוח',
    'cookie.tahini': 'טחינה',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'ביסקוויט לוטוס וממרח קרמל',
    'cookie.kinderDesc': 'שוקולד קינדר וכדורי שוקולד צבעוניים',
    'cookie.kinderBuenoDesc': 'קינדר בואנו, שוקולד חלב וציפוי שוקולד',
    'cookie.redVelvetDesc': 'בצק רד וולווט, שוקולד לבן ופירורי פטל',
    'cookie.confettiDesc': 'סוכריות צבעוניות וסמארטיז',
    'cookie.pistachioDesc': 'שוקולד לבן, פיסטוקים קלויים וגרגירי רימון',
    'cookie.pretzelDesc': 'בייגלה מלוח, שוקולד לבן וצ׳יפס שוקולד',
    'cookie.chocolateChipDesc': 'צ׳יפס שוקולד בלגי מריר ושוקולד חלב',
    'cookie.oreoDesc': 'פירורי אוראו, שוקולד לבן וקרם וניל',
    'cookie.peanutButterDesc': 'חמאת בוטנים, בוטנים קלויים ושוקולד',
    'cookie.lemonDesc': 'גרידת לימון טרי וציפוי סוכר',
    'cookie.macadamiaDesc': 'אגוזי מקדמיה ושוקולד לבן',
    'cookie.oatmealDesc': 'שיבולת שועל, צימוקים וקינמון',
    'cookie.saltedCaramelDesc': 'קרמל ביתי וקריסטלי מלח ים',
    'cookie.tahiniDesc': 'טחינה גולמית, שומשום ודבש',
    
    // Cookie of the Week
    'cotw.title': 'עוגיית השבוע',
    'cotw.discount': 'הנחה',
    'cotw.originalPrice': 'מחיר מקורי',
    'cotw.salePrice': 'מחיר מבצע',
    
    // About
    'about.title': 'אודות מזון האושר',
    'about.ourStory': 'הסיפור שלנו',
    'about.headline': 'יוצרים אושר, יצירה אחת בכל פעם',
    'about.description': 'מזון האושר התחיל במטבח ביתי קטן עם חלום פשוט: לשתף את החום והנוחות של מאפים ביתיים עם הקהילה שלנו.',
    'about.madeWithLove': 'מיוצר באהבה',
    'about.madeWithLoveDesc': 'כל אצווה מוכנה בקפידה ובתשוקה, בדיוק כמו שסבתא הייתה עושה.',
    'about.freshIngredients': 'מרכיבים טריים',
    'about.freshIngredientsDesc': 'אנחנו מקפידים רק על המרכיבים הטריים והמשובחים ביותר.',
    'about.dailyPrep': 'הכנה יומית',
    'about.dailyPrepDesc': 'המוצרים שלנו מוכנים טריים כל בוקר לטעם מושלם.',
    
    // Reviews
    'reviews.title': 'מה הלקוחות אומרים',
    'reviews.subtitle': 'ביקורות מלקוחות מרוצים',
    'reviews.addReview': 'הוסיפו ביקורת',
    'reviews.selectProduct': 'בחרו מוצר',
    'reviews.selectProductPlaceholder': 'בחרו מוצר...',
    'reviews.rating': 'דירוג',
    'reviews.yourReview': 'הביקורת שלכם (אופציונלי, עד 500 תווים)',
    'reviews.reviewPlaceholder': 'ספרו לנו מה חשבתם...',
    'reviews.submit': 'לשלוח ביקורת',
    'reviews.submitting': 'שולח...',
    'reviews.loginRequired': 'כדי לכתוב ביקורת צריך להתחבר',
    'reviews.recentReviews': 'ביקורות אחרונות',
    'reviews.filterAll': 'כל המוצרים',
    'reviews.noReviews': 'אין עדיין ביקורות. היו הראשונים לכתוב ביקורת!',
    'reviews.thankYou': 'תודה על הביקורת! 🍪',
    'reviews.reviewAdded': 'הביקורת שלך נוספה בהצלחה',
    'reviews.reviewsCount': 'ביקורות',
    
    // FAQ
    'faq.title': 'שאלות נפוצות',
    'faq.subtitle': 'כאן תמצאו תשובות לשאלות הנפוצות ביותר. לא מצאתם מה שחיפשתם? צרו איתנו קשר!',
    'faq.delivery': 'איך עובד המשלוח?',
    'faq.deliveryAnswer': 'המשלוחים מתבצעים בימים א׳-ה׳ בשעות 10:00-20:00. המשלוח עולה ₪25 לכל הארץ, ומשלוח חינם בהזמנות מעל ₪150. זמן האספקה הוא 1-3 ימי עסקים.',
    'faq.payment': 'אילו אמצעי תשלום מקבלים?',
    'faq.paymentAnswer': 'כרגע אנחנו מקבלים תשלום במזומן בלבד בעת קבלת המשלוח. בקרוב נוסיף אפשרות לתשלום בכרטיס אשראי.',
    'faq.freshness': 'כמה זמן המוצרים נשמרים טריים?',
    'faq.freshnessAnswer': 'המוצרים שלנו מוכנים טריים לכל הזמנה ונשמרים טריים עד 5 ימים בטמפרטורת החדר או עד שבועיים במקרר. מומלץ לחמם במיקרוגל 10 שניות לחוויה מושלמת!',
    'faq.allergens': 'מה לגבי אלרגנים?',
    'faq.allergensAnswer': 'כל העוגיות שלנו מכילות גלוטן, חלב וביצים. חלק מהעוגיות מכילות אגוזים, בוטנים או סויה. אם יש לכם אלרגיה מסוימת, אנא ציינו בהערות ההזמנה ונתאים עבורכם.',
    'faq.events': 'האם אפשר להזמין לאירועים?',
    'faq.eventsAnswer': 'בהחלט! אנחנו מציעים חבילות מיוחדות לאירועים, ימי הולדת, חתונות ובת/בר מצווה. צרו איתנו קשר לקבלת הצעת מחיר מותאמת אישית.',
    'faq.contact': 'איך יוצרים איתכם קשר?',
    'faq.contactAnswer': 'אפשר ליצור קשר דרך הוואטסאפ בכפתור הצף למטה, דרך הטופס באתר, או בטלפון 054-6791198. אנחנו זמינים בימים א׳-ה׳ בין השעות 9:00-21:00.',
    
    // Contact
    'contact.title': 'צרו קשר',
    'contact.address': 'שדרות קדש 39, אשקלון',
    'contact.phone': '054-679-1198',
    'contact.hours': 'אספקה עד 3 ימי עסקים',
    
    // Cart
    'cart.title': 'העגלה שלך',
    'cart.empty': 'העגלה ריקה',
    'cart.total': 'סה"כ',
    'cart.checkout': 'לתשלום',
    'cart.remove': 'הסר',
    'cart.quantity': 'כמות',
    'cart.subtotal': 'סכום ביניים',
    'cart.shipping': 'משלוח',
    'cart.free': 'חינם',
    
    // Checkout
    'checkout.title': 'פרטי הזמנה',
    'checkout.name': 'שם מלא',
    'checkout.phone': 'טלפון',
    'checkout.address': 'כתובת',
    'checkout.city': 'עיר',
    'checkout.notes': 'הערות להזמנה',
    'checkout.submit': 'שלח הזמנה',
    'checkout.success': 'ההזמנה נשלחה בהצלחה!',
    
    // Auth (basic - extended auth keys are at the end of Hebrew section)
    'auth.login': 'התחברות',
    'auth.signup': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.loginButton': 'התחבר',
    'auth.signupButton': 'הירשם',
    'auth.orContinueWith': 'או המשך עם',
    'auth.phoneLogin': 'התחברות עם טלפון',
    'auth.verifyCode': 'אמת קוד',

    // Profile
    'profile.title': 'הפרופיל שלי',
    'profile.edit': 'ערוך פרופיל',
    'profile.save': 'שמור',
    'profile.cancel': 'ביטול',
    'profile.deleteAccount': 'מחיקת חשבון',
    'profile.changePassword': 'שנה סיסמה',
    
    // Newsletter
    'newsletter.title': 'לא לפספס מבצעים!',
    'newsletter.subtitle': 'הירשמו לניוזלטר וקבלו עדכונים על מבצעים מיוחדים',
    'newsletter.emailPlaceholder': 'כתובת המייל שלך',
    'newsletter.phonePlaceholder': 'מספר טלפון (אופציונלי)',
    'newsletter.button': 'להירשם לעדכונים ✨',
    'newsletter.submitting': 'שולח...',
    'newsletter.success': 'נרשמת בהצלחה! 🎉',
    'newsletter.successDesc': 'תקבל/י עדכונים על מבצעים וחדשות',
    'newsletter.thankYou': 'תודה שנרשמת! ✨',
    'newsletter.thankYouDesc': 'נעדכן אותך על מבצעים מיוחדים, מוצרים חדשים והפתעות מתוקות',
    'newsletter.noSpam': 'אנחנו מבטיחים לא לשלוח ספאם. רק טוב טעים. ✨',
    
    // Footer
    'footer.rights': 'כל הזכויות שמורות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    
    // General
    'general.loading': 'טוען...',
    'general.error': 'שגיאה',
    'general.success': 'הצלחה',
    'general.close': 'סגור',
    'general.back': 'חזרה',
    'general.next': 'הבא',
    'general.confirm': 'אישור',
    'general.delete': 'מחק',
    'general.edit': 'ערוך',
    'general.save': 'שמור',
    'general.cancel': 'ביטול',
    
    // Gift Package
    'gift.title': 'חבילות מתנה',
    'gift.subtitle': 'בנו חבילת מתנה מושלמת עם העוגיות האהובות עליכם',
    'gift.selectCookies': 'בחרו עוגיות למארז',
    'gift.packageName': 'שם המארז',
    'gift.packageNameOptional': 'שם החבילה (אופציונלי)',
    'gift.packageNamePlaceholder': 'למשל: מתנה ליום הולדת',
    'gift.addToCart': 'להוסיף לעגלה',
    'gift.small': 'חבילה קטנה',
    'gift.medium': 'חבילה בינונית',
    'gift.large': 'חבילה גדולה',
    'gift.smallDesc': '6 עוגיות לבחירתך',
    'gift.mediumDesc': '12 עוגיות לבחירתך',
    'gift.largeDesc': '24 עוגיות לבחירתך',
    'gift.discount': 'הנחה',
    'gift.selected': 'נבחרו',
    'gift.outOf': 'מתוך',
    'gift.moreToSelect': 'עוד {count} לבחירה',
    'gift.packageFull': 'החבילה מלאה!',
    'gift.packageFullError': 'החבילה מלאה',
    'gift.alreadySelected': 'בחרת כבר {count} עוגיות',
    'gift.yourCookies': 'העוגיות שבחרתם',
    'gift.regularPrice': 'מחיר רגיל:',
    'gift.packageDiscount': 'הנחת חבילה',
    'gift.total': 'סה״כ:',
    'gift.notComplete': 'החבילה לא מלאה',
    'gift.selectMore': 'נא לבחור {count} עוגיות נוספות',
    'gift.addedToCart': 'החבילה נוספה לעגלה! 🎁',
    'gift.cookies': 'עוגיות',
    
    // Cookie of the Week
    'cotw.badge': 'עוגיית השבוע',
    'cotw.add': 'הוספה',
    
    // Cart Modal
    'cartModal.title': 'העגלה שלי',
    'cartModal.completing': 'השלמת הזמנה',
    'cartModal.empty': 'העגלה ריקה',
    'cartModal.addCookies': 'הוסיפו עוגיות טעימות!',
    'cartModal.cookies': 'עוגיות',
    'cartModal.saved': 'חסכת',
    'cartModal.total': 'סה״כ:',
    'cartModal.continue': 'המשך להזמנה',
    'cartModal.maxItems': 'מקסימום 6 יחידות לפריט',
    
    // Checkout Form
    'checkoutForm.back': 'חזרה לעגלה',
    'checkoutForm.loginRequired': 'נדרשת התחברות',
    'checkoutForm.loginRequiredDesc': 'כדי להשלים את ההזמנה, יש להתחבר או להירשם. הפרטים שלך יישמרו להזמנות הבאות!',
    'checkoutForm.loginSignup': 'התחברות / הרשמה',
    'checkoutForm.connectedAs': 'מחובר כ:',
    'checkoutForm.orderDetails': 'פרטי הזמנה',
    'checkoutForm.fullName': 'שם מלא',
    'checkoutForm.namePlaceholder': 'ישראל ישראלי',
    'checkoutForm.email': 'מייל',
    'checkoutForm.phone': 'טלפון',
    'checkoutForm.city': 'עיר',
    'checkoutForm.cityPlaceholder': 'תל אביב',
    'checkoutForm.address': 'כתובת',
    'checkoutForm.addressPlaceholder': 'רחוב הרצל 1',
    'checkoutForm.notes': 'הערות למשלוח (אופציונלי, עד 500 תווים)',
    'checkoutForm.notesPlaceholder': 'קומה, דירה, הוראות מיוחדות...',
    'checkoutForm.totalPayment': 'סה״כ לתשלום:',
    'checkoutForm.cashPayment': '💵 תשלום במזומן בעת המשלוח',
    'checkoutForm.orderCash': 'להזמין במזומן',
    'checkoutForm.sending': 'שולח...',
    'checkoutForm.confirmationSent': 'נשלח אישור למייל ולוואטסאפ',
    'checkoutForm.tooManyOrders': 'יותר מדי הזמנות. נסו שוב מאוחר יותר.',
    'checkoutForm.orderSuccess': 'ההזמנה נשלחה בהצלחה! נשלח מייל ווואטסאפ',
    'checkoutForm.orderError': 'שגיאה בשליחת ההזמנה, נסו שוב',
    
    // Order History
    'orderHistory.title': 'היסטוריית הזמנות',
    'orderHistory.myOrders': 'ההזמנות שלי',
    'orderHistory.subtitle': 'צפייה והזמנה חוזרת של הזמנות קודמות',
    'orderHistory.loginPrompt': 'התחברו כדי לראות את ההזמנות הקודמות',
    'orderHistory.login': 'התחברות',
    'orderHistory.loading': 'טוען הזמנות...',
    'orderHistory.noOrders': 'אין הזמנות קודמות',
    'orderHistory.ordersWillAppear': 'ההזמנות שלכם יופיעו כאן',
    'orderHistory.reorder': 'הזמנה חוזרת',
    'orderHistory.itemsAdded': 'הפריטים נוספו לעגלה!',
    'orderHistory.pending': 'ממתין לאישור',
    'orderHistory.confirmed': 'אושר',
    'orderHistory.preparing': 'בהכנה',
    'orderHistory.delivering': 'במשלוח',
    'orderHistory.completed': 'הושלם',
    'orderHistory.cancelled': 'בוטל',
    
    // Edit Profile Modal
    'editProfile.title': 'עריכת פרופיל',
    'editProfile.clickToChange': 'לחץ להחלפת תמונה',
    'editProfile.imageOnly': 'יש להעלות קובץ תמונה בלבד',
    'editProfile.maxSize': 'גודל התמונה מקסימלי 2MB',
    'editProfile.uploadSuccess': 'התמונה הועלתה בהצלחה!',
    'editProfile.uploadError': 'שגיאה בהעלאת התמונה',
    'editProfile.emailLabel': 'אימייל',
    'editProfile.fullNameLabel': 'שם מלא',
    'editProfile.namePlaceholder': 'השם שלך',
    'editProfile.phoneLabel': 'טלפון *',
    'editProfile.phonePlaceholder': '054-1234567',
    'editProfile.cityLabel': 'עיר',
    'editProfile.cityPlaceholder': 'שם העיר',
    'editProfile.addressLabel': 'כתובת',
    'editProfile.addressPlaceholder': 'רחוב ומספר בית',
    'editProfile.notesLabel': 'הערות למשלוח',
    'editProfile.notesPlaceholder': 'קוד בניין, קומה, הוראות מיוחדות...',
    'editProfile.save': 'שמור שינויים',
    'editProfile.saving': 'שומר...',
    'editProfile.success': 'הפרופיל עודכן בהצלחה! ✨',
    'editProfile.deleteAccount': 'מחיקת חשבון',
    
    // Change Password Modal
    'changePassword.title': 'שינוי סיסמה',
    'changePassword.currentPassword': 'סיסמה נוכחית',
    'changePassword.currentPlaceholder': 'הזן סיסמה נוכחית',
    'changePassword.newPassword': 'סיסמה חדשה',
    'changePassword.newPlaceholder': 'לפחות 8 תווים',
    'changePassword.confirmPassword': 'אימות סיסמה',
    'changePassword.confirmPlaceholder': 'הזן שוב את הסיסמה',
    'changePassword.requirements': 'אות גדולה + מספר + 8 תווים לפחות',
    'changePassword.change': 'שנה סיסמה',
    'changePassword.changing': 'מעדכן...',
    'changePassword.success': 'הסיסמה שונתה בהצלחה!',
    'changePassword.successDesc': 'השתמש בסיסמה החדשה בהתחברות הבאה',
    'changePassword.wrongCurrent': 'סיסמה נוכחית שגויה',
    'changePassword.noUser': 'לא נמצא משתמש מחובר',
    
    // Delete Account Modal
    'deleteAccount.title': 'מחיקת חשבון',
    'deleteAccount.typeConfirm': 'כדי להמשיך, הקלד',
    'deleteAccount.deleteWord': 'מחיקה',
    'deleteAccount.typePlaceholder': 'הקלד מחיקה',
    'deleteAccount.warning': 'פעולה זו תמחק לצמיתות את החשבון שלך וכל המידע הקשור אליו, כולל:',
    'deleteAccount.profileData': 'פרטי הפרופיל',
    'deleteAccount.orderHistory': 'היסטוריית הזמנות',
    'deleteAccount.noRecover': 'לא ניתן לשחזר את המידע לאחר המחיקה!',
    'deleteAccount.sendCode': 'נשלח קוד אימות למייל',
    'deleteAccount.continue': 'המשך',
    'deleteAccount.continueDelete': 'המשך למחיקה',
    'deleteAccount.sendingCode': 'שולח קוד...',
    'deleteAccount.enterCode': 'הזן את קוד האימות שנשלח למייל שלך:',
    'deleteAccount.enter6Digits': 'יש להזין 6 ספרות',
    'deleteAccount.resendIn': 'שלח שוב בעוד {seconds} שניות',
    'deleteAccount.resend': 'שלח קוד חדש',
    'deleteAccount.back': 'חזור',
    'deleteAccount.cancel': 'ביטול',
    'deleteAccount.deleting': 'מוחק...',
    'deleteAccount.deletePermanently': 'מחק לצמיתות',
    'deleteAccount.deleted': 'החשבון נמחק',
    'deleteAccount.goodbye': 'להתראות, תמיד אפשר לחזור 🍪',
    'deleteAccount.noEmail': 'לא נמצא אימייל משתמש',
    'deleteAccount.codeSent': 'קוד נשלח! 📧',
    'deleteAccount.checkEmail': 'בדוק את תיבת המייל שלך',
    
    // Cookie Card
    'cookieCard.added': 'נוסף!',
    'cookieCard.add': 'הוסף',
    'cookieCard.addToCart': 'הוסף לעגלה',
    'cookieCard.recommended': 'מומלץ',
    'cookieCard.new': 'חדש',
    'cookieCard.maxItems': 'מקסימום 6 יחידות לפריט',
    'cookieCard.readMore': 'קרא עוד על',
    
    // Auth Modal
    'auth.loginTitle': 'התחברות',
    'auth.registerTitle': 'הרשמה',
    'auth.forgotTitle': 'שכחתי סיסמה',
    'auth.otpTitle': 'אימות דו-שלבי',
    'auth.smsLoginTitle': 'התחברות ב-SMS',
    'auth.smsOtpTitle': 'אימות SMS',
    'auth.smsLoginDesc': 'הזן את מספר הטלפון שלך ונשלח לך קוד אימות ב-SMS',
    'auth.phoneLabel': 'מספר טלפון *',
    'auth.sendCode': 'שלח קוד אימות',
    'auth.sending': 'שולח...',
    'auth.backToLogin': 'חזרה להתחברות רגילה',
    'auth.codeSentTo': 'שלחנו קוד אימות בן 6 ספרות ל-',
    'auth.verifying': 'מאמת...',
    'auth.verify': 'אמת',
    'auth.resendIn': 'שלח שוב בעוד {seconds} שניות',
    'auth.resendCode': 'שלח קוד חדש',
    'auth.back': 'חזרה',
    'auth.rememberDevice': 'זכור את המכשיר הזה',
    'auth.verifyAndContinue': 'אמת והמשך',
    'auth.smsLogin': 'התחברות ב-SMS',
    'auth.or': 'או',
    'auth.fullNameLabel': 'שם מלא *',
    'auth.fullNamePlaceholder': 'ישראל ישראלי',
    'auth.phoneOptional': 'טלפון',
    'auth.emailLabel': 'אימייל *',
    'auth.passwordLabel': 'סיסמה *',
    'auth.passwordPlaceholder': 'לפחות 6 תווים',
    'auth.forgotPassword': 'שכחתי סיסמה',
    'auth.loggingIn': 'מתחבר...',
    'auth.registering': 'נרשם...',
    'auth.sendingReset': 'שולח...',
    'auth.loginBtn': 'התחברות',
    'auth.registerBtn': 'הרשמה',
    'auth.sendResetLink': 'שלח קישור לאיפוס',
    'auth.backToLoginLink': 'חזרה להתחברות',
    'auth.noAccount': 'אין לך חשבון?',
    'auth.hasAccount': 'כבר יש לך חשבון?',
    'auth.signupLink': 'הירשם',
    'auth.loginLink': 'התחבר',
    'auth.tooManyAttempts': 'יותר מדי ניסיונות שגויים. נסה שוב בעוד {minutes} דקות',
    'auth.wrongCode': 'קוד אימות שגוי',
    'auth.attemptsLeft': 'נותרו {count} ניסיונות',
    'auth.enter6Digits': 'יש להזין 6 ספרות',
    'auth.invalidPhone': 'מספר טלפון לא תקין',
    'auth.phoneTooLong': 'מספר טלפון ארוך מדי',
    'auth.israeliPhoneRequired': 'יש להזין מספר טלפון נייד ישראלי תקין',
    'auth.invalidEmail': 'כתובת אימייל לא תקינה',
    'auth.passwordMin': 'סיסמה חייבת להכיל לפחות 6 תווים',
    'auth.nameMin': 'שם חייב להכיל לפחות 2 תווים',
    'auth.nameTooLong': 'שם ארוך מדי',
    'auth.codeSentEmail': 'קוד נשלח! 📧',
    'auth.checkEmailInbox': 'בדוק את תיבת המייל שלך',
    'auth.codeSentSms': 'קוד נשלח! 📱',
    'auth.checkSms': 'בדוק את הודעות ה-SMS שלך',
    'auth.resetSent': 'נשלח בהצלחה! 📧',
    'auth.resetSentDesc': 'קישור לאיפוס סיסמה נשלח לאימייל שלך',
    'auth.wrongCredentials': 'אימייל או סיסמה שגויים',
    'auth.emailExists': 'כתובת האימייל כבר רשומה במערכת',
    'auth.cancelledLogin': 'ההתחברות בוטלה',
    'auth.popupClosed': 'החלון נסגר לפני השלמת ההתחברות',
    'auth.networkError': 'שגיאת רשת, בדוק את החיבור לאינטרנט',
    'auth.providerNotEnabled': 'ספק ההתחברות לא מוגדר כרגע',
    'auth.unknownDevice': 'מכשיר לא ידוע',
    'auth.error': 'שגיאה',
    'auth.genericError': 'אירעה שגיאה, נסו שוב',
    'auth.sendCodeError': 'אירעה שגיאה בשליחת הקוד',
    'auth.sessionError': 'שגיאה בהתחברות',
    
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.cookies': 'Cookies',
    'nav.about': 'About',
    'nav.reviews': 'Reviews',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.orderHistory': 'Order History',
    'nav.editProfile': 'Edit Profile',
    
    // Hero
    'hero.title': 'Mazon HaOsher',
    'hero.subtitle': 'Giant American Cookies',
    'hero.description': 'Handcrafted giant American cookies made from the finest ingredients',
    'hero.cta': 'View Our Cookies',
    'hero.madeWithLove': 'Made with Love',
    'hero.viewMenu': 'View Menu',
    
    // Cookies Section
    'cookies.title': 'Our Collection',
    'cookies.subtitle': 'Made with love, especially for you ✨',
    'cookies.addToCart': 'Add to Cart',
    'cookies.outOfStock': 'Out of Stock',
    'cookies.price': '₪',
    'cookies.search': 'Search...',
    'cookies.all': 'All',
    'cookies.chocolate': 'Chocolate',
    'cookies.fruits': 'Fruits',
    'cookies.candy': 'Candy',
    'cookies.nuts': 'Nuts',
    'cookies.classic': 'Classic',
    'cookies.recommended': 'Recommended',
    'cookies.new': 'New',
    'cookies.favorites': 'Favorites',
    'cookies.sortDefault': 'Default',
    'cookies.sortName': 'By Name',
    'cookies.sortPrice': 'By Price',
    'cookies.noResults': 'No cookies found',
    'cookies.clearFilters': 'Clear filters',
    
    // Cookie names
    'cookie.lotus': 'Lotus',
    'cookie.kinder': 'Kinder',
    'cookie.kinderBueno': 'Kinder Bueno',
    'cookie.redVelvet': 'Red Velvet',
    'cookie.confetti': 'Confetti',
    'cookie.pistachio': 'Pistachio',
    'cookie.pretzel': 'Pretzel',
    'cookie.chocolateChip': 'Chocolate Chip',
    'cookie.oreo': 'Oreo',
    'cookie.peanutButter': 'Peanut Butter',
    'cookie.lemon': 'Lemon',
    'cookie.macadamia': 'Macadamia',
    'cookie.oatmeal': 'Oatmeal',
    'cookie.saltedCaramel': 'Salted Caramel',
    'cookie.tahini': 'Tahini',
    
    // Cookie descriptions
    'cookie.lotusDesc': 'Lotus biscuit and caramel spread',
    'cookie.kinderDesc': 'Kinder chocolate with colorful chocolate balls',
    'cookie.kinderBuenoDesc': 'Kinder Bueno, milk chocolate and chocolate coating',
    'cookie.redVelvetDesc': 'Red velvet dough, white chocolate and raspberry crumbs',
    'cookie.confettiDesc': 'Colorful sprinkles and Smarties',
    'cookie.pistachioDesc': 'White chocolate, roasted pistachios and pomegranate seeds',
    'cookie.pretzelDesc': 'Salted pretzel, white chocolate and chocolate chips',
    'cookie.chocolateChipDesc': 'Belgian dark and milk chocolate chips',
    'cookie.oreoDesc': 'Oreo crumbs, white chocolate and vanilla cream',
    'cookie.peanutButterDesc': 'Peanut butter, roasted peanuts and chocolate',
    'cookie.lemonDesc': 'Fresh lemon zest with sugar coating',
    'cookie.macadamiaDesc': 'Macadamia nuts and white chocolate',
    'cookie.oatmealDesc': 'Oatmeal, raisins and cinnamon',
    'cookie.saltedCaramelDesc': 'Homemade caramel with sea salt crystals',
    'cookie.tahiniDesc': 'Raw tahini, sesame seeds and honey',
    
    // Cookie of the Week
    'cotw.title': 'Cookie of the Week',
    'cotw.discount': 'OFF',
    'cotw.originalPrice': 'Original Price',
    'cotw.salePrice': 'Sale Price',
    
    // About
    'about.title': 'About Mazon HaOsher',
    'about.ourStory': 'Our Story',
    'about.headline': 'Creating happiness, one creation at a time',
    'about.description': 'Mazon HaOsher started in a small home kitchen with a simple dream: to share the warmth and comfort of homemade baked goods with our community.',
    'about.madeWithLove': 'Made with Love',
    'about.madeWithLoveDesc': 'Every batch is prepared with care and passion, just like grandma used to make.',
    'about.freshIngredients': 'Fresh Ingredients',
    'about.freshIngredientsDesc': 'We use only the freshest and finest ingredients.',
    'about.dailyPrep': 'Daily Preparation',
    'about.dailyPrepDesc': 'Our products are freshly prepared every morning for perfect taste.',
    
    // Reviews
    'reviews.title': 'What Our Customers Say',
    'reviews.subtitle': 'Reviews from happy customers',
    'reviews.addReview': 'Add a Review',
    'reviews.selectProduct': 'Select a product',
    'reviews.selectProductPlaceholder': 'Select a product...',
    'reviews.rating': 'Rating',
    'reviews.yourReview': 'Your review (optional, up to 500 characters)',
    'reviews.reviewPlaceholder': 'Tell us what you thought...',
    'reviews.submit': 'Submit Review',
    'reviews.submitting': 'Submitting...',
    'reviews.loginRequired': 'You need to log in to write a review',
    'reviews.recentReviews': 'Recent Reviews',
    'reviews.filterAll': 'All Products',
    'reviews.noReviews': 'No reviews yet. Be the first to write a review!',
    'reviews.thankYou': 'Thanks for your review! 🍪',
    'reviews.reviewAdded': 'Your review has been added successfully',
    'reviews.reviewsCount': 'reviews',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': "Here you'll find answers to the most common questions. Didn't find what you're looking for? Contact us!",
    'faq.delivery': 'How does delivery work?',
    'faq.deliveryAnswer': 'Deliveries are made Sunday-Thursday, 10:00-20:00. Shipping costs ₪25 nationwide, free shipping on orders over ₪150. Delivery time is 1-3 business days.',
    'faq.payment': 'What payment methods do you accept?',
    'faq.paymentAnswer': 'Currently we accept cash payment upon delivery only. Credit card payment will be added soon.',
    'faq.freshness': 'How long do the products stay fresh?',
    'faq.freshnessAnswer': 'Our products are freshly made for each order and stay fresh for up to 5 days at room temperature or up to two weeks in the refrigerator. We recommend heating in the microwave for 10 seconds for the perfect experience!',
    'faq.allergens': 'What about allergens?',
    'faq.allergensAnswer': 'All our cookies contain gluten, dairy and eggs. Some cookies contain nuts, peanuts or soy. If you have a specific allergy, please note it in your order and we will accommodate you.',
    'faq.events': 'Can I order for events?',
    'faq.eventsAnswer': 'Absolutely! We offer special packages for events, birthdays, weddings and bar/bat mitzvahs. Contact us for a personalized quote.',
    'faq.contact': 'How can I contact you?',
    'faq.contactAnswer': 'You can contact us via WhatsApp using the floating button below, through the website form, or by phone at 054-6791198. We are available Sunday-Thursday between 9:00-21:00.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.address': '39 Kadesh Blvd, Ashkelon',
    'contact.phone': '054-679-1198',
    'contact.hours': 'Delivery within 3 business days',
    
    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.free': 'Free',
    
    // Checkout
    'checkout.title': 'Order Details',
    'checkout.name': 'Full Name',
    'checkout.phone': 'Phone',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.notes': 'Order Notes',
    'checkout.submit': 'Place Order',
    'checkout.success': 'Order placed successfully!',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.orContinueWith': 'Or continue with',
    'auth.phoneLogin': 'Login with Phone',
    'auth.verifyCode': 'Verify Code',
    'auth.loginTitle': 'Login',
    'auth.registerTitle': 'Sign Up',
    'auth.forgotTitle': 'Forgot Password',
    'auth.otpTitle': 'Two-Factor Auth',
    'auth.smsLoginTitle': 'SMS Login',
    'auth.smsOtpTitle': 'SMS Verification',
    'auth.smsLoginDesc': 'Enter your phone number and we will send you a verification code via SMS',
    'auth.phoneLabel': 'Phone Number *',
    'auth.sendCode': 'Send Code',
    'auth.sending': 'Sending...',
    'auth.backToLogin': 'Back to regular login',
    'auth.codeSentTo': 'We sent a 6-digit verification code to',
    'auth.verifying': 'Verifying...',
    'auth.verify': 'Verify',
    'auth.resendIn': 'Resend in {seconds} seconds',
    'auth.resendCode': 'Send new code',
    'auth.back': 'Back',
    'auth.rememberDevice': 'Remember this device',
    'auth.verifyAndContinue': 'Verify and continue',
    'auth.smsLogin': 'SMS Login',
    'auth.or': 'or',
    'auth.fullNameLabel': 'Full Name *',
    'auth.fullNamePlaceholder': 'John Doe',
    'auth.phoneOptional': 'Phone',
    'auth.emailLabel': 'Email *',
    'auth.passwordLabel': 'Password *',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Signing up...',
    'auth.sendingReset': 'Sending...',
    'auth.loginBtn': 'Login',
    'auth.registerBtn': 'Sign Up',
    'auth.sendResetLink': 'Send reset link',
    'auth.backToLoginLink': 'Back to login',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signupLink': 'Sign up',
    'auth.loginLink': 'Log in',
    'auth.loginButton': 'Log In',
    'auth.signupButton': 'Sign Up',
    'auth.tooManyAttempts': 'Too many failed attempts. Try again in {minutes} minutes',
    'auth.wrongCode': 'Invalid verification code',
    'auth.attemptsLeft': '{count} attempts remaining',
    'auth.enter6Digits': 'Please enter 6 digits',
    'auth.invalidPhone': 'Invalid phone number',
    'auth.phoneTooLong': 'Phone number too long',
    'auth.israeliPhoneRequired': 'Please enter a valid Israeli mobile number',
    'auth.invalidEmail': 'Invalid email address',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.nameMin': 'Name must be at least 2 characters',
    'auth.nameTooLong': 'Name is too long',
    'auth.codeSentEmail': 'Code sent! 📧',
    'auth.checkEmailInbox': 'Check your email inbox',
    'auth.codeSentSms': 'Code sent! 📱',
    'auth.checkSms': 'Check your SMS messages',
    'auth.resetSent': 'Sent successfully! 📧',
    'auth.resetSentDesc': 'A password reset link was sent to your email',
    'auth.wrongCredentials': 'Invalid email or password',
    'auth.emailExists': 'This email is already registered',
    'auth.cancelledLogin': 'Login was cancelled',
    'auth.popupClosed': 'The window was closed before completing login',
    'auth.networkError': 'Network error, check your internet connection',
    'auth.providerNotEnabled': 'This login provider is not currently configured',
    'auth.unknownDevice': 'Unknown device',
    'auth.error': 'Error',
    'auth.genericError': 'An error occurred, please try again',
    'auth.sendCodeError': 'An error occurred while sending the code',
    'auth.sessionError': 'Login error',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.deleteAccount': 'Delete Account',
    'profile.changePassword': 'Change Password',
    
    // Newsletter
    'newsletter.title': "Don't Miss Out!",
    'newsletter.subtitle': 'Subscribe to our newsletter for special offers',
    'newsletter.emailPlaceholder': 'Your email address',
    'newsletter.phonePlaceholder': 'Phone number (optional)',
    'newsletter.button': 'Subscribe for updates ✨',
    'newsletter.submitting': 'Submitting...',
    'newsletter.success': 'Subscribed successfully! 🎉',
    'newsletter.successDesc': "You'll receive updates on deals and news",
    'newsletter.thankYou': 'Thanks for subscribing! ✨',
    'newsletter.thankYouDesc': "We'll update you on special deals, new products and sweet surprises",
    'newsletter.noSpam': "We promise not to send spam. Only delicious updates. ✨",
    
    // Footer
    'footer.rights': 'All Rights Reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.close': 'Close',
    'general.back': 'Back',
    'general.next': 'Next',
    'general.confirm': 'Confirm',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    
    // Gift Package
    'gift.title': 'Gift Packages',
    'gift.subtitle': 'Build the perfect gift package with your favorite cookies',
    'gift.selectCookies': 'Select cookies for the package',
    'gift.packageName': 'Package Name',
    'gift.packageNameOptional': 'Package name (optional)',
    'gift.packageNamePlaceholder': 'e.g., Birthday gift',
    'gift.addToCart': 'Add to Cart',
    'gift.small': 'Small Package',
    'gift.medium': 'Medium Package',
    'gift.large': 'Large Package',
    'gift.smallDesc': '6 cookies of your choice',
    'gift.mediumDesc': '12 cookies of your choice',
    'gift.largeDesc': '24 cookies of your choice',
    'gift.discount': 'OFF',
    'gift.selected': 'Selected',
    'gift.outOf': 'out of',
    'gift.moreToSelect': '{count} more to select',
    'gift.packageFull': 'Package complete!',
    'gift.packageFullError': 'Package is full',
    'gift.alreadySelected': 'You already selected {count} cookies',
    'gift.yourCookies': 'Your selected cookies',
    'gift.regularPrice': 'Regular price:',
    'gift.packageDiscount': 'Package discount',
    'gift.total': 'Total:',
    'gift.notComplete': 'Package not complete',
    'gift.selectMore': 'Please select {count} more cookies',
    'gift.addedToCart': 'Package added to cart! 🎁',
    'gift.cookies': 'cookies',
    
    // Cookie of the Week
    'cotw.badge': 'Cookie of the Week',
    'cotw.add': 'Add',
    
    // Cart Modal
    'cartModal.title': 'My Cart',
    'cartModal.completing': 'Complete Order',
    'cartModal.empty': 'Cart is empty',
    'cartModal.addCookies': 'Add some delicious cookies!',
    'cartModal.cookies': 'cookies',
    'cartModal.saved': 'You saved',
    'cartModal.total': 'Total:',
    'cartModal.continue': 'Continue to Order',
    'cartModal.maxItems': 'Maximum 6 items per product',
    
    // Checkout Form
    'checkoutForm.back': 'Back to cart',
    'checkoutForm.loginRequired': 'Login Required',
    'checkoutForm.loginRequiredDesc': 'To complete your order, please login or sign up. Your details will be saved for future orders!',
    'checkoutForm.loginSignup': 'Login / Sign Up',
    'checkoutForm.connectedAs': 'Connected as:',
    'checkoutForm.orderDetails': 'Order Details',
    'checkoutForm.fullName': 'Full Name',
    'checkoutForm.namePlaceholder': 'John Doe',
    'checkoutForm.email': 'Email',
    'checkoutForm.phone': 'Phone',
    'checkoutForm.city': 'City',
    'checkoutForm.cityPlaceholder': 'Tel Aviv',
    'checkoutForm.address': 'Address',
    'checkoutForm.addressPlaceholder': '1 Herzl St',
    'checkoutForm.notes': 'Delivery notes (optional, up to 500 characters)',
    'checkoutForm.notesPlaceholder': 'Floor, apartment, special instructions...',
    'checkoutForm.totalPayment': 'Total to pay:',
    'checkoutForm.cashPayment': '💵 Cash payment upon delivery',
    'checkoutForm.orderCash': 'Order with Cash',
    'checkoutForm.sending': 'Sending...',
    'checkoutForm.confirmationSent': 'Confirmation sent via email and WhatsApp',
    'checkoutForm.tooManyOrders': 'Too many orders. Try again later.',
    'checkoutForm.orderSuccess': 'Order sent successfully! Email and WhatsApp sent',
    'checkoutForm.orderError': 'Error sending order, please try again',
    
    // Order History
    'orderHistory.title': 'Order History',
    'orderHistory.myOrders': 'My Orders',
    'orderHistory.subtitle': 'View and reorder previous orders',
    'orderHistory.loginPrompt': 'Login to see your previous orders',
    'orderHistory.login': 'Login',
    'orderHistory.loading': 'Loading orders...',
    'orderHistory.noOrders': 'No previous orders',
    'orderHistory.ordersWillAppear': 'Your orders will appear here',
    'orderHistory.reorder': 'Reorder',
    'orderHistory.itemsAdded': 'Items added to cart!',
    'orderHistory.pending': 'Pending',
    'orderHistory.confirmed': 'Confirmed',
    'orderHistory.preparing': 'Preparing',
    'orderHistory.delivering': 'Delivering',
    'orderHistory.completed': 'Completed',
    'orderHistory.cancelled': 'Cancelled',
    
    // Edit Profile Modal
    'editProfile.title': 'Edit Profile',
    'editProfile.clickToChange': 'Click to change photo',
    'editProfile.imageOnly': 'Please upload an image file only',
    'editProfile.maxSize': 'Maximum image size is 2MB',
    'editProfile.uploadSuccess': 'Image uploaded successfully!',
    'editProfile.uploadError': 'Error uploading image',
    'editProfile.emailLabel': 'Email',
    'editProfile.fullNameLabel': 'Full Name',
    'editProfile.namePlaceholder': 'Your name',
    'editProfile.phoneLabel': 'Phone *',
    'editProfile.phonePlaceholder': '054-1234567',
    'editProfile.cityLabel': 'City',
    'editProfile.cityPlaceholder': 'City name',
    'editProfile.addressLabel': 'Address',
    'editProfile.addressPlaceholder': 'Street and house number',
    'editProfile.notesLabel': 'Delivery notes',
    'editProfile.notesPlaceholder': 'Building code, floor, special instructions...',
    'editProfile.save': 'Save Changes',
    'editProfile.saving': 'Saving...',
    'editProfile.success': 'Profile updated successfully! ✨',
    'editProfile.deleteAccount': 'Delete Account',
    
    // Change Password Modal
    'changePassword.title': 'Change Password',
    'changePassword.currentPassword': 'Current Password',
    'changePassword.currentPlaceholder': 'Enter current password',
    'changePassword.newPassword': 'New Password',
    'changePassword.newPlaceholder': 'At least 8 characters',
    'changePassword.confirmPassword': 'Confirm Password',
    'changePassword.confirmPlaceholder': 'Enter password again',
    'changePassword.requirements': 'Uppercase letter + number + at least 8 characters',
    'changePassword.change': 'Change Password',
    'changePassword.changing': 'Updating...',
    'changePassword.success': 'Password changed successfully!',
    'changePassword.successDesc': 'Use your new password on next login',
    'changePassword.wrongCurrent': 'Current password is incorrect',
    'changePassword.noUser': 'No logged in user found',
    
    // Delete Account Modal
    'deleteAccount.title': 'Delete Account',
    'deleteAccount.typeConfirm': 'To continue, type',
    'deleteAccount.deleteWord': 'delete',
    'deleteAccount.typePlaceholder': 'Type delete',
    'deleteAccount.warning': 'This action will permanently delete your account and all associated data, including:',
    'deleteAccount.profileData': 'Profile data',
    'deleteAccount.orderHistory': 'Order history',
    'deleteAccount.noRecover': 'Data cannot be recovered after deletion!',
    'deleteAccount.sendCode': 'A verification code will be sent to email',
    'deleteAccount.continue': 'Continue',
    'deleteAccount.continueDelete': 'Continue to delete',
    'deleteAccount.sendingCode': 'Sending code...',
    'deleteAccount.enterCode': 'Enter the verification code sent to your email:',
    'deleteAccount.enter6Digits': 'Please enter 6 digits',
    'deleteAccount.resendIn': 'Resend in {seconds} seconds',
    'deleteAccount.resend': 'Send new code',
    'deleteAccount.back': 'Back',
    'deleteAccount.cancel': 'Cancel',
    'deleteAccount.deleting': 'Deleting...',
    'deleteAccount.deletePermanently': 'Delete permanently',
    'deleteAccount.deleted': 'Account deleted',
    'deleteAccount.goodbye': 'Goodbye, you can always come back 🍪',
    'deleteAccount.noEmail': 'No user email found',
    'deleteAccount.codeSent': 'Code sent! 📧',
    'deleteAccount.checkEmail': 'Check your email inbox',
    
    // Cookie Card
    'cookieCard.added': 'Added!',
    'cookieCard.add': 'Add',
    'cookieCard.addToCart': 'Add to Cart',
    'cookieCard.recommended': 'Recommended',
    'cookieCard.new': 'New',
    'cookieCard.maxItems': 'Maximum 6 items per product',
    'cookieCard.readMore': 'Read more about',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'he';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    // Update document direction and lang
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
